// [AUTO-GENERATED by @wink-ai/unisim-ui/generator or aligned with wokwi-ntc-temperature-sensor]
// Source: wokwi-ntc-temperature-sensor
import type { PinsOverlayMap } from '@wink-ai/unisim-ui';

export const NTC_AUTOGEN_SIZE = Object.freeze({
  width: 135,
  height: 72,
});

export const NTC_AUTOGEN_OVERLAY: Readonly<PinsOverlayMap> = Object.freeze({
  GND: Object.freeze({
    relX: 135,
    relY: 26,
    wireNet: 'gnd' as const,
    defaultConnection: 'GND' as const,
    required: false,
  }),
  VCC: Object.freeze({
    relX: 135,
    relY: 36,
    wireNet: 'vcc' as const,
    defaultConnection: 'VCC' as const,
    required: false,
  }),
  OUT: Object.freeze({
    relX: 135,
    relY: 46,
    wireNet: 'primary' as const,
    defaultConnection: null,
    required: true,
  }),
});
