/* SPDX-License-Identifier: LGPL-3.0-only */
/* Harvested from esp-idf v6.1@fff9895c (Apache-2.0) — factual C-ABI only, comments stripped. See NOTICE. */
/* AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY! Manifest: 542eb37a5dc3604c Source: v6.1@fff9895c Config: esp32/v6.1 */
#ifndef WINK_H_GUARD_SOC_SOC_CAPS_H
#define WINK_H_GUARD_SOC_SOC_CAPS_H
#ifndef __WINK_HARVESTED_SOC_SOC_CAPS_H__
#define __WINK_HARVESTED_SOC_SOC_CAPS_H__
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "wink_sla.h"

#include "sdkconfig.h"
#include "soc/soc_caps_eval.h"

#ifdef __cplusplus
extern "C" {
#endif
/* --- Macros (object + allowlisted function-like; first-wins + #ifndef wrapped) --- */
#ifndef SOC_ADC_ATTEN_NUM
#define SOC_ADC_ATTEN_NUM (4)
#endif
#ifndef SOC_ADC_CHANNEL_NUM
#define SOC_ADC_CHANNEL_NUM(PERIPH_NUM) ((PERIPH_NUM==0)? 8: 10)
#endif
#ifndef SOC_ADC_DIGI_CONTROLLER_NUM
#define SOC_ADC_DIGI_CONTROLLER_NUM (2)
#endif
#ifndef SOC_ADC_DIGI_DATA_BYTES_PER_CONV
#define SOC_ADC_DIGI_DATA_BYTES_PER_CONV (4)
#endif
#ifndef SOC_ADC_DIGI_MAX_BITWIDTH
#define SOC_ADC_DIGI_MAX_BITWIDTH (12)
#endif
#ifndef SOC_ADC_DIGI_MIN_BITWIDTH
#define SOC_ADC_DIGI_MIN_BITWIDTH (9)
#endif
#ifndef SOC_ADC_DIGI_MONITOR_NUM
#define SOC_ADC_DIGI_MONITOR_NUM (0U)
#endif
#ifndef SOC_ADC_DIGI_RESULT_BYTES
#define SOC_ADC_DIGI_RESULT_BYTES (2)
#endif
#ifndef SOC_ADC_DIG_CTRL_SUPPORTED
#define SOC_ADC_DIG_CTRL_SUPPORTED 1
#endif
#ifndef SOC_ADC_DIG_SUPPORTED_UNIT
#define SOC_ADC_DIG_SUPPORTED_UNIT(UNIT) ((UNIT == 0) ? 1 : 0)
#endif
#ifndef SOC_ADC_DMA_SUPPORTED
#define SOC_ADC_DMA_SUPPORTED 1
#endif
#ifndef SOC_ADC_MAX_CHANNEL_NUM
#define SOC_ADC_MAX_CHANNEL_NUM (10)
#endif
#ifndef SOC_ADC_PATT_LEN_MAX
#define SOC_ADC_PATT_LEN_MAX (16)
#endif
#ifndef SOC_ADC_PERIPH_NUM
#define SOC_ADC_PERIPH_NUM (2)
#endif
#ifndef SOC_ADC_RTC_CTRL_SUPPORTED
#define SOC_ADC_RTC_CTRL_SUPPORTED 1
#endif
#ifndef SOC_ADC_RTC_MAX_BITWIDTH
#define SOC_ADC_RTC_MAX_BITWIDTH (12)
#endif
#ifndef SOC_ADC_RTC_MIN_BITWIDTH
#define SOC_ADC_RTC_MIN_BITWIDTH (9)
#endif
#ifndef SOC_ADC_SAMPLE_FREQ_THRES_HIGH
#define SOC_ADC_SAMPLE_FREQ_THRES_HIGH (2000000)
#endif
#ifndef SOC_ADC_SAMPLE_FREQ_THRES_LOW
#define SOC_ADC_SAMPLE_FREQ_THRES_LOW (20000)
#endif
#ifndef SOC_ADC_SHARED_POWER
#define SOC_ADC_SHARED_POWER 1
#endif
#ifndef SOC_ADC_SUPPORTED
#define SOC_ADC_SUPPORTED 1
#endif
#ifndef SOC_AES_SUPPORTED
#define SOC_AES_SUPPORTED 1
#endif
#ifndef SOC_AES_SUPPORT_AES_128
#define SOC_AES_SUPPORT_AES_128 (1)
#endif
#ifndef SOC_AES_SUPPORT_AES_192
#define SOC_AES_SUPPORT_AES_192 (1)
#endif
#ifndef SOC_AES_SUPPORT_AES_256
#define SOC_AES_SUPPORT_AES_256 (1)
#endif
#ifndef SOC_BLE_DEVICE_PRIVACY_SUPPORTED
#define SOC_BLE_DEVICE_PRIVACY_SUPPORTED (0)
#endif
#ifndef SOC_BLE_MESH_SUPPORTED
#define SOC_BLE_MESH_SUPPORTED (1)
#endif
#ifndef SOC_BLE_MULTI_CONN_OPTIMIZATION
#define SOC_BLE_MULTI_CONN_OPTIMIZATION (1)
#endif
#ifndef SOC_BLE_SUPPORTED
#define SOC_BLE_SUPPORTED (1)
#endif
#ifndef SOC_BLUFI_SUPPORTED
#define SOC_BLUFI_SUPPORTED (1)
#endif
#ifndef SOC_BOD_SUPPORTED
#define SOC_BOD_SUPPORTED 1
#endif
#ifndef SOC_BT_CLASSIC_SUPPORTED
#define SOC_BT_CLASSIC_SUPPORTED (1)
#endif
#ifndef SOC_BT_H2C_ENC_KEY_CTRL_ENH_VSC_SUPPORTED
#define SOC_BT_H2C_ENC_KEY_CTRL_ENH_VSC_SUPPORTED (1)
#endif
#ifndef SOC_BT_SUPPORTED
#define SOC_BT_SUPPORTED 1
#endif
#ifndef SOC_CAPS_ECO_VER
#define SOC_CAPS_ECO_VER CONFIG_ESP32_REV_MIN_FULL
#endif
#ifndef SOC_CAPS_ECO_VER_MAX
#define SOC_CAPS_ECO_VER_MAX 301
#endif
#ifndef SOC_CCOMP_TIMER_SUPPORTED
#define SOC_CCOMP_TIMER_SUPPORTED 1
#endif
#ifndef SOC_CLK_APLL_SUPPORTED
#define SOC_CLK_APLL_SUPPORTED (1)
#endif
#ifndef SOC_CLK_LP_FAST_SUPPORT_XTAL_D4
#define SOC_CLK_LP_FAST_SUPPORT_XTAL_D4 (1)
#endif
#ifndef SOC_CLK_RC_FAST_D256_SUPPORTED
#define SOC_CLK_RC_FAST_D256_SUPPORTED (1)
#endif
#ifndef SOC_CLK_RC_FAST_SUPPORT_CALIBRATION
#define SOC_CLK_RC_FAST_SUPPORT_CALIBRATION (1)
#endif
#ifndef SOC_CLK_TREE_SUPPORTED
#define SOC_CLK_TREE_SUPPORTED 1
#endif
#ifndef SOC_CLK_XTAL32K_SUPPORTED
#define SOC_CLK_XTAL32K_SUPPORTED (1)
#endif
#ifndef SOC_CONFIGURABLE_VDDSDIO_SUPPORTED
#define SOC_CONFIGURABLE_VDDSDIO_SUPPORTED (1)
#endif
#ifndef SOC_CPU_BREAKPOINTS_NUM
#define SOC_CPU_BREAKPOINTS_NUM 2
#endif
#ifndef SOC_CPU_CORES_NUM
#define SOC_CPU_CORES_NUM 2
#endif
#ifndef SOC_CPU_HAS_FPU
#define SOC_CPU_HAS_FPU 1
#endif
#ifndef SOC_CPU_INTR_NUM
#define SOC_CPU_INTR_NUM 32
#endif
#ifndef SOC_CPU_WATCHPOINTS_NUM
#define SOC_CPU_WATCHPOINTS_NUM 2
#endif
#ifndef SOC_CPU_WATCHPOINT_MAX_REGION_SIZE
#define SOC_CPU_WATCHPOINT_MAX_REGION_SIZE 0x40
#endif
#ifndef SOC_DAC_CHAN_NUM
#define SOC_DAC_CHAN_NUM 2
#endif
#ifndef SOC_DAC_DMA_16BIT_ALIGN
#define SOC_DAC_DMA_16BIT_ALIGN 1
#endif
#ifndef SOC_DAC_RESOLUTION
#define SOC_DAC_RESOLUTION 8
#endif
#ifndef SOC_DAC_SUPPORTED
#define SOC_DAC_SUPPORTED 1
#endif
#ifndef SOC_DEEP_SLEEP_SUPPORTED
#define SOC_DEEP_SLEEP_SUPPORTED 1
#endif
#ifndef SOC_DPORT_WORKAROUND
#define SOC_DPORT_WORKAROUND 1
#endif
#ifndef SOC_DPORT_WORKAROUND_DIS_INTERRUPT_LVL
#define SOC_DPORT_WORKAROUND_DIS_INTERRUPT_LVL (5U)
#endif
#ifndef SOC_EFUSE_SECURE_BOOT_KEY_DIGESTS
#define SOC_EFUSE_SECURE_BOOT_KEY_DIGESTS (1U)
#endif
#ifndef SOC_EFUSE_SUPPORTED
#define SOC_EFUSE_SUPPORTED 1
#endif
#ifndef SOC_EMAC_REF_CLK_FROM_APLL
#define SOC_EMAC_REF_CLK_FROM_APLL (1)
#endif
#ifndef SOC_EMAC_RMII_CLK_OUT_INTERNAL_LOOPBACK
#define SOC_EMAC_RMII_CLK_OUT_INTERNAL_LOOPBACK (1)
#endif
#ifndef SOC_EMAC_SUPPORTED
#define SOC_EMAC_SUPPORTED 1
#endif
#ifndef SOC_FLASH_ENCRYPTED_XTS_AES_BLOCK_MAX
#define SOC_FLASH_ENCRYPTED_XTS_AES_BLOCK_MAX (32)
#endif
#ifndef SOC_FLASH_ENC_SUPPORTED
#define SOC_FLASH_ENC_SUPPORTED 1
#endif
#ifndef SOC_GPIO_CLOCKOUT_BY_IO_MUX
#define SOC_GPIO_CLOCKOUT_BY_IO_MUX (1)
#endif
#ifndef SOC_GPIO_CLOCKOUT_CHANNEL_NUM
#define SOC_GPIO_CLOCKOUT_CHANNEL_NUM (3)
#endif
#ifndef SOC_GPIO_HP_PERIPH_PD_SLEEP_WAKEABLE_MASK
#define SOC_GPIO_HP_PERIPH_PD_SLEEP_WAKEABLE_MASK (0ULL | BIT0 | BIT2 | BIT4 | BIT12 | BIT13 | BIT14 | BIT15 | BIT25 | BIT26 | BIT27 | BIT32 | BIT33 | BIT34 | BIT35 | BIT36 | BIT37 | BIT38 | BIT39)
#endif
#ifndef SOC_GPIO_IN_RANGE_MAX
#define SOC_GPIO_IN_RANGE_MAX 39
#endif
#ifndef SOC_GPIO_OUT_RANGE_MAX
#define SOC_GPIO_OUT_RANGE_MAX 33
#endif
#ifndef SOC_GPIO_PIN_COUNT
#define SOC_GPIO_PIN_COUNT 40
#endif
#ifndef SOC_GPIO_PORT
#define SOC_GPIO_PORT (1U)
#endif
#ifndef SOC_GPIO_SUPPORT_DEEPSLEEP_WAKEUP
#define SOC_GPIO_SUPPORT_DEEPSLEEP_WAKEUP SOC_GPIO_SUPPORT_HP_PERIPH_PD_SLEEP_WAKEUP
#endif
#ifndef SOC_GPIO_SUPPORT_HP_PERIPH_PD_SLEEP_WAKEUP
#define SOC_GPIO_SUPPORT_HP_PERIPH_PD_SLEEP_WAKEUP (1)
#endif
#ifndef SOC_GPIO_VALID_DIGITAL_IO_PAD_MASK
#define SOC_GPIO_VALID_DIGITAL_IO_PAD_MASK 0xEF0FEAULL
#endif
#ifndef SOC_GPIO_VALID_GPIO_MASK
#define SOC_GPIO_VALID_GPIO_MASK (0xFFFFFFFFFFULL & ~(0ULL | BIT24 | BIT28 | BIT29 | BIT30 | BIT31))
#endif
#ifndef SOC_GPIO_VALID_OUTPUT_GPIO_MASK
#define SOC_GPIO_VALID_OUTPUT_GPIO_MASK (SOC_GPIO_VALID_GPIO_MASK & ~(0ULL | BIT34 | BIT35 | BIT36 | BIT37 | BIT38 | BIT39))
#endif
#ifndef SOC_GPSPI_SUPPORTED
#define SOC_GPSPI_SUPPORTED 1
#endif
#ifndef SOC_GPTIMER_SUPPORTED
#define SOC_GPTIMER_SUPPORTED 1
#endif
#ifndef SOC_HP_CPU_HAS_MULTIPLE_CORES
#define SOC_HP_CPU_HAS_MULTIPLE_CORES 1
#endif
#ifndef SOC_HP_I2C_NUM
#define SOC_HP_I2C_NUM (2U)
#endif
#ifndef SOC_I2C_NUM
#define SOC_I2C_NUM (2U)
#endif
#ifndef SOC_I2C_STOP_INDEPENDENT
#define SOC_I2C_STOP_INDEPENDENT (1)
#endif
#ifndef SOC_I2C_SUPPORTED
#define SOC_I2C_SUPPORTED 1
#endif
#ifndef SOC_I2C_SUPPORT_10BIT_ADDR
#define SOC_I2C_SUPPORT_10BIT_ADDR (1)
#endif
#ifndef SOC_I2C_SUPPORT_APB
#define SOC_I2C_SUPPORT_APB (1)
#endif
#ifndef SOC_I2C_SUPPORT_SLAVE
#define SOC_I2C_SUPPORT_SLAVE (1)
#endif
#ifndef SOC_I2S_HW_VERSION_1
#define SOC_I2S_HW_VERSION_1 (1)
#endif
#ifndef SOC_I2S_I80_LCD_SUPPORTED
#define SOC_I2S_I80_LCD_SUPPORTED 1
#endif
#ifndef SOC_I2S_PDM_MAX_RX_LINES
#define SOC_I2S_PDM_MAX_RX_LINES (1U)
#endif
#ifndef SOC_I2S_PDM_MAX_TX_LINES
#define SOC_I2S_PDM_MAX_TX_LINES (1U)
#endif
#ifndef SOC_I2S_SUPPORTED
#define SOC_I2S_SUPPORTED 1
#endif
#ifndef SOC_I2S_SUPPORTS_APLL
#define SOC_I2S_SUPPORTS_APLL (1)
#endif
#ifndef SOC_I2S_SUPPORTS_PCM2PDM
#define SOC_I2S_SUPPORTS_PCM2PDM (1)
#endif
#ifndef SOC_I2S_SUPPORTS_PDM
#define SOC_I2S_SUPPORTS_PDM (1)
#endif
#ifndef SOC_I2S_SUPPORTS_PDM2PCM
#define SOC_I2S_SUPPORTS_PDM2PCM (1)
#endif
#ifndef SOC_I2S_SUPPORTS_PDM_RX
#define SOC_I2S_SUPPORTS_PDM_RX (1)
#endif
#ifndef SOC_I2S_SUPPORTS_PDM_TX
#define SOC_I2S_SUPPORTS_PDM_TX (1)
#endif
#ifndef SOC_IDCACHE_PER_CORE
#define SOC_IDCACHE_PER_CORE 1
#endif
#ifndef SOC_LCD_I80_SUPPORTED
#define SOC_LCD_I80_SUPPORTED 1
#endif
#ifndef SOC_LEDC_CHANNEL_NUM
#define SOC_LEDC_CHANNEL_NUM (8)
#endif
#ifndef SOC_LEDC_HAS_TIMER_SPECIFIC_MUX
#define SOC_LEDC_HAS_TIMER_SPECIFIC_MUX (1)
#endif
#ifndef SOC_LEDC_SUPPORTED
#define SOC_LEDC_SUPPORTED 1
#endif
#ifndef SOC_LEDC_SUPPORT_APB_CLOCK
#define SOC_LEDC_SUPPORT_APB_CLOCK (1)
#endif
#ifndef SOC_LEDC_SUPPORT_HS_MODE
#define SOC_LEDC_SUPPORT_HS_MODE (1)
#endif
#ifndef SOC_LEDC_SUPPORT_REF_TICK
#define SOC_LEDC_SUPPORT_REF_TICK (1)
#endif
#ifndef SOC_LEDC_TIMER_BIT_WIDTH
#define SOC_LEDC_TIMER_BIT_WIDTH (20)
#endif
#ifndef SOC_LEDC_TIMER_NUM
#define SOC_LEDC_TIMER_NUM (4)
#endif
#ifndef SOC_LIGHT_SLEEP_SUPPORTED
#define SOC_LIGHT_SLEEP_SUPPORTED 1
#endif
#ifndef SOC_LP_PERIPH_SHARE_INTERRUPT
#define SOC_LP_PERIPH_SHARE_INTERRUPT 1
#endif
#ifndef SOC_LP_TIMER_BIT_WIDTH_HI
#define SOC_LP_TIMER_BIT_WIDTH_HI 16
#endif
#ifndef SOC_LP_TIMER_BIT_WIDTH_LO
#define SOC_LP_TIMER_BIT_WIDTH_LO 32
#endif
#ifndef SOC_MCPWM_SUPPORTED
#define SOC_MCPWM_SUPPORTED 1
#endif
#ifndef SOC_MEMSPI_ENCRYPTION_ALIGNMENT
#define SOC_MEMSPI_ENCRYPTION_ALIGNMENT 16
#endif
#ifndef SOC_MMU_LINEAR_ADDRESS_REGION_NUM
#define SOC_MMU_LINEAR_ADDRESS_REGION_NUM 3
#endif
#ifndef SOC_MMU_PERIPH_NUM
#define SOC_MMU_PERIPH_NUM 2
#endif
#ifndef SOC_MPI_MEM_BLOCKS_NUM
#define SOC_MPI_MEM_BLOCKS_NUM (4)
#endif
#ifndef SOC_MPI_OPERATIONS_NUM
#define SOC_MPI_OPERATIONS_NUM (1U)
#endif
#ifndef SOC_MPI_SUPPORTED
#define SOC_MPI_SUPPORTED 1
#endif
#ifndef SOC_MPU_CONFIGURABLE_REGIONS_SUPPORTED
#define SOC_MPU_CONFIGURABLE_REGIONS_SUPPORTED 0
#endif
#ifndef SOC_MPU_MIN_REGION_SIZE
#define SOC_MPU_MIN_REGION_SIZE 0x20000000U
#endif
#ifndef SOC_MPU_REGIONS_MAX_NUM
#define SOC_MPU_REGIONS_MAX_NUM 8
#endif
#ifndef SOC_MPU_REGION_RO_SUPPORTED
#define SOC_MPU_REGION_RO_SUPPORTED 0
#endif
#ifndef SOC_MPU_REGION_WO_SUPPORTED
#define SOC_MPU_REGION_WO_SUPPORTED 0
#endif
#ifndef SOC_MPU_SUPPORTED
#define SOC_MPU_SUPPORTED 1
#endif
#ifndef SOC_PCNT_SUPPORTED
#define SOC_PCNT_SUPPORTED 1
#endif
#ifndef SOC_PHY_COMBO_MODULE
#define SOC_PHY_COMBO_MODULE (1)
#endif
#ifndef SOC_PHY_DIG_REGS_MEM_SIZE
#define SOC_PHY_DIG_REGS_MEM_SIZE (21*4)
#endif
#ifndef SOC_PHY_SUPPORTED
#define SOC_PHY_SUPPORTED 1
#endif
#ifndef SOC_PM_MODEM_PD_BY_SW
#define SOC_PM_MODEM_PD_BY_SW (1)
#endif
#ifndef SOC_PM_RTC_NOT_SUPPORT_UART2_WAKEUP
#define SOC_PM_RTC_NOT_SUPPORT_UART2_WAKEUP (1)
#endif
#ifndef SOC_PM_SUPPORTED
#define SOC_PM_SUPPORTED 1
#endif
#ifndef SOC_PM_SUPPORT_EXT0_WAKEUP
#define SOC_PM_SUPPORT_EXT0_WAKEUP (1)
#endif
#ifndef SOC_PM_SUPPORT_EXT1_WAKEUP
#define SOC_PM_SUPPORT_EXT1_WAKEUP (1)
#endif
#ifndef SOC_PM_SUPPORT_EXT_WAKEUP
#define SOC_PM_SUPPORT_EXT_WAKEUP (1)
#endif
#ifndef SOC_PM_SUPPORT_MODEM_PD
#define SOC_PM_SUPPORT_MODEM_PD (1)
#endif
#ifndef SOC_PM_SUPPORT_RC_FAST_PD
#define SOC_PM_SUPPORT_RC_FAST_PD (1)
#endif
#ifndef SOC_PM_SUPPORT_RTC_FAST_MEM_PD
#define SOC_PM_SUPPORT_RTC_FAST_MEM_PD (1)
#endif
#ifndef SOC_PM_SUPPORT_RTC_PERIPH_PD
#define SOC_PM_SUPPORT_RTC_PERIPH_PD (1)
#endif
#ifndef SOC_PM_SUPPORT_RTC_SLOW_MEM_PD
#define SOC_PM_SUPPORT_RTC_SLOW_MEM_PD (1)
#endif
#ifndef SOC_PM_SUPPORT_TOUCH_SENSOR_WAKEUP
#define SOC_PM_SUPPORT_TOUCH_SENSOR_WAKEUP (1)
#endif
#ifndef SOC_PM_SUPPORT_VDDSDIO_PD
#define SOC_PM_SUPPORT_VDDSDIO_PD (1)
#endif
#ifndef SOC_REGI2C_SUPPORTED
#define SOC_REGI2C_SUPPORTED 1
#endif
#ifndef SOC_RMT_MEM_WORDS_PER_CHANNEL
#define SOC_RMT_MEM_WORDS_PER_CHANNEL 64
#endif
#ifndef SOC_RMT_SUPPORTED
#define SOC_RMT_SUPPORTED 1
#endif
#ifndef SOC_RNG_SUPPORTED
#define SOC_RNG_SUPPORTED 1
#endif
#ifndef SOC_RSA_MAX_BIT_LEN
#define SOC_RSA_MAX_BIT_LEN (4096)
#endif
#ifndef SOC_RTCIO_HOLD_SUPPORTED
#define SOC_RTCIO_HOLD_SUPPORTED 1
#endif
#ifndef SOC_RTCIO_INPUT_OUTPUT_SUPPORTED
#define SOC_RTCIO_INPUT_OUTPUT_SUPPORTED 1
#endif
#ifndef SOC_RTCIO_PIN_COUNT
#define SOC_RTCIO_PIN_COUNT 18
#endif
#ifndef SOC_RTCIO_WAKE_SUPPORTED
#define SOC_RTCIO_WAKE_SUPPORTED 1
#endif
#ifndef SOC_RTC_CNTL_NEEDS_ATOMIC_ACCESS
#define SOC_RTC_CNTL_NEEDS_ATOMIC_ACCESS 1
#endif
#ifndef SOC_RTC_FAST_MEM_SUPPORTED
#define SOC_RTC_FAST_MEM_SUPPORTED 1
#endif
#ifndef SOC_RTC_MEM_SUPPORTED
#define SOC_RTC_MEM_SUPPORTED 1
#endif
#ifndef SOC_RTC_SLOW_CLK_SUPPORT_RC_FAST_D256
#define SOC_RTC_SLOW_CLK_SUPPORT_RC_FAST_D256 (1)
#endif
#ifndef SOC_RTC_SLOW_MEM_SUPPORTED
#define SOC_RTC_SLOW_MEM_SUPPORTED 1
#endif
#ifndef SOC_RTC_TIMER_SUPPORTED
#define SOC_RTC_TIMER_SUPPORTED 1
#endif
#ifndef SOC_RTC_TIMER_V1
#define SOC_RTC_TIMER_V1 1
#endif
#ifndef SOC_RTC_WDT_SUPPORTED
#define SOC_RTC_WDT_SUPPORTED 1
#endif
#ifndef SOC_SDIO_SLAVE_SUPPORTED
#define SOC_SDIO_SLAVE_SUPPORTED 1
#endif
#ifndef SOC_SDMMC_DATA_WIDTH_MAX
#define SOC_SDMMC_DATA_WIDTH_MAX 8
#endif
#ifndef SOC_SDMMC_HOST_SUPPORTED
#define SOC_SDMMC_HOST_SUPPORTED 1
#endif
#ifndef SOC_SDMMC_NUM_SLOTS
#define SOC_SDMMC_NUM_SLOTS 2
#endif
#ifndef SOC_SDMMC_USE_IOMUX
#define SOC_SDMMC_USE_IOMUX 1
#endif
#ifndef SOC_SDM_SUPPORTED
#define SOC_SDM_SUPPORTED 1
#endif
#ifndef SOC_SECURE_BOOT_SUPPORTED
#define SOC_SECURE_BOOT_SUPPORTED 1
#endif
#ifndef SOC_SECURE_BOOT_V1
#define SOC_SECURE_BOOT_V1 1
#endif
#ifndef SOC_SHARED_IDCACHE_SUPPORTED
#define SOC_SHARED_IDCACHE_SUPPORTED 1
#endif
#ifndef SOC_SHA_ENDIANNESS_BE
#define SOC_SHA_ENDIANNESS_BE (1)
#endif
#ifndef SOC_SHA_SUPPORTED
#define SOC_SHA_SUPPORTED 1
#endif
#ifndef SOC_SHA_SUPPORT_PARALLEL_ENG
#define SOC_SHA_SUPPORT_PARALLEL_ENG (1)
#endif
#ifndef SOC_SHA_SUPPORT_SHA1
#define SOC_SHA_SUPPORT_SHA1 (1)
#endif
#ifndef SOC_SHA_SUPPORT_SHA256
#define SOC_SHA_SUPPORT_SHA256 (1)
#endif
#ifndef SOC_SHA_SUPPORT_SHA384
#define SOC_SHA_SUPPORT_SHA384 (1)
#endif
#ifndef SOC_SHA_SUPPORT_SHA512
#define SOC_SHA_SUPPORT_SHA512 (1)
#endif
#ifndef SOC_SPIRAM_SUPPORTED
#define SOC_SPIRAM_SUPPORTED 1
#endif
#ifndef SOC_SPI_EXTERNAL_NOR_FLASH_SUPPORTED
#define SOC_SPI_EXTERNAL_NOR_FLASH_SUPPORTED 1
#endif
#ifndef SOC_SPI_FLASH_SUPPORTED
#define SOC_SPI_FLASH_SUPPORTED 1
#endif
#ifndef SOC_SPI_HD_BOTH_INOUT_SUPPORTED
#define SOC_SPI_HD_BOTH_INOUT_SUPPORTED 1
#endif
#ifndef SOC_SPI_MAXIMUM_BUFFER_SIZE
#define SOC_SPI_MAXIMUM_BUFFER_SIZE 64
#endif
#ifndef SOC_SPI_MEM_SUPPORT_CONFIG_GPIO_BY_EFUSE
#define SOC_SPI_MEM_SUPPORT_CONFIG_GPIO_BY_EFUSE (1)
#endif
#ifndef SOC_SPI_PERIPH_NUM
#define SOC_SPI_PERIPH_NUM 3
#endif
#ifndef SOC_SUPPORT_COEXISTENCE
#define SOC_SUPPORT_COEXISTENCE 1
#endif
#ifndef SOC_TOUCH_MAX_CHAN_ID
#define SOC_TOUCH_MAX_CHAN_ID (9)
#endif
#ifndef SOC_TOUCH_MIN_CHAN_ID
#define SOC_TOUCH_MIN_CHAN_ID (0U)
#endif
#ifndef SOC_TOUCH_SAMPLE_CFG_NUM
#define SOC_TOUCH_SAMPLE_CFG_NUM (1U)
#endif
#ifndef SOC_TOUCH_SENSOR_SUPPORTED
#define SOC_TOUCH_SENSOR_SUPPORTED 1
#endif
#ifndef SOC_TOUCH_SENSOR_VERSION
#define SOC_TOUCH_SENSOR_VERSION (1U)
#endif
#ifndef SOC_TOUCH_SUPPORT_SLEEP_WAKEUP
#define SOC_TOUCH_SUPPORT_SLEEP_WAKEUP (1)
#endif
#ifndef SOC_TWAI_CONTROLLER_NUM
#define SOC_TWAI_CONTROLLER_NUM 1U
#endif
#ifndef SOC_TWAI_MASK_FILTER_NUM
#define SOC_TWAI_MASK_FILTER_NUM 1U
#endif
#ifndef SOC_TWAI_SUPPORTED
#define SOC_TWAI_SUPPORTED 1
#endif
#ifndef SOC_UART_BITRATE_MAX
#define SOC_UART_BITRATE_MAX (5000000)
#endif
#ifndef SOC_UART_FIFO_LEN
#define SOC_UART_FIFO_LEN (128)
#endif
#ifndef SOC_UART_HP_NUM
#define SOC_UART_HP_NUM (3)
#endif
#ifndef SOC_UART_NUM
#define SOC_UART_NUM (3)
#endif
#ifndef SOC_UART_SUPPORTED
#define SOC_UART_SUPPORTED 1
#endif
#ifndef SOC_UART_SUPPORT_APB_CLK
#define SOC_UART_SUPPORT_APB_CLK (1)
#endif
#ifndef SOC_UART_SUPPORT_REF_TICK
#define SOC_UART_SUPPORT_REF_TICK (1)
#endif
#ifndef SOC_UART_WAKEUP_SUPPORT_ACTIVE_THRESH_MODE
#define SOC_UART_WAKEUP_SUPPORT_ACTIVE_THRESH_MODE (1)
#endif
#ifndef SOC_ULP_FSM_SUPPORTED
#define SOC_ULP_FSM_SUPPORTED 1
#endif
#ifndef SOC_ULP_HAS_ADC
#define SOC_ULP_HAS_ADC (1)
#endif
#ifndef SOC_ULP_SUPPORTED
#define SOC_ULP_SUPPORTED 1
#endif
#ifndef SOC_WDT_SUPPORTED
#define SOC_WDT_SUPPORTED 1
#endif
#ifndef SOC_WIFI_CSI_SUPPORT
#define SOC_WIFI_CSI_SUPPORT (1)
#endif
#ifndef SOC_WIFI_MESH_SUPPORT
#define SOC_WIFI_MESH_SUPPORT (1)
#endif
#ifndef SOC_WIFI_NAN_SUPPORT
#define SOC_WIFI_NAN_SUPPORT (1)
#endif
#ifndef SOC_WIFI_SUPPORTED
#define SOC_WIFI_SUPPORTED 1
#endif
#ifndef SOC_WIFI_SUPPORT_VARIABLE_BEACON_WINDOW
#define SOC_WIFI_SUPPORT_VARIABLE_BEACON_WINDOW (1)
#endif
#ifndef SOC_WIFI_WAPI_SUPPORT
#define SOC_WIFI_WAPI_SUPPORT (1)
#endif
#ifndef SOC_XTAL_SUPPORT_26M
#define SOC_XTAL_SUPPORT_26M 1
#endif
#ifndef SOC_XTAL_SUPPORT_40M
#define SOC_XTAL_SUPPORT_40M 1
#endif
#ifndef _SOC_CAPS_TARGET_IS_ESP32
#define _SOC_CAPS_TARGET_IS_ESP32 1
#endif

/* --- Enums (implicit values backfilled; ABI attrs preserved) --- */

/* --- Structs & Typedefs (merged, source order preserved for C forward refs) --- */



#ifdef __cplusplus
}
#endif
#endif /* __WINK_HARVESTED_SOC_SOC_CAPS_H__ */
#endif /* WINK_H_GUARD_SOC_SOC_CAPS_H */
