/* SPDX-License-Identifier: LGPL-3.0-only */
/* Harvested from esp-idf v6.1@fff9895c (Apache-2.0) — factual C-ABI only, comments stripped. See NOTICE. */
/* AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY! Manifest: 542eb37a5dc3604c Source: v6.1@fff9895c Config: esp32/v6.1 */
#ifndef _CACHE_MEMORY_H_
#define _CACHE_MEMORY_H_
#ifndef __WINK_HARVESTED_SOC_EXT_MEM_DEFS_H__
#define __WINK_HARVESTED_SOC_EXT_MEM_DEFS_H__
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "wink_sla.h"

#include "esp_bit_defs.h"

#ifdef __cplusplus
extern "C" {
#endif
/* --- Macros (object + allowlisted function-like; first-wins + #ifndef wrapped) --- */
#ifndef SOC_ADDRESS_IN_BUS
#define SOC_ADDRESS_IN_BUS(bus_name, vaddr) ((vaddr) >= bus_name##_ADDRESS_LOW && (vaddr) < bus_name##_ADDRESS_HIGH)
#endif
#ifndef SOC_ADDRESS_IN_DRAM1_CACHE
#define SOC_ADDRESS_IN_DRAM1_CACHE(vaddr) SOC_ADDRESS_IN_BUS(SOC_DRAM1_CACHE, vaddr)
#endif
#ifndef SOC_ADDRESS_IN_DROM0_CACHE
#define SOC_ADDRESS_IN_DROM0_CACHE(vaddr) SOC_ADDRESS_IN_BUS(SOC_DROM0_CACHE, vaddr)
#endif
#ifndef SOC_ADDRESS_IN_IRAM0_CACHE
#define SOC_ADDRESS_IN_IRAM0_CACHE(vaddr) SOC_ADDRESS_IN_BUS(SOC_IRAM0_CACHE, vaddr)
#endif
#ifndef SOC_ADDRESS_IN_IRAM1_CACHE
#define SOC_ADDRESS_IN_IRAM1_CACHE(vaddr) SOC_ADDRESS_IN_BUS(SOC_IRAM1_CACHE, vaddr)
#endif
#ifndef SOC_ADDRESS_IN_IROM0_CACHE
#define SOC_ADDRESS_IN_IROM0_CACHE(vaddr) SOC_ADDRESS_IN_BUS(SOC_IROM0_CACHE, vaddr)
#endif
#ifndef SOC_BUS_SIZE
#define SOC_BUS_SIZE(bus_name) (bus_name##_ADDRESS_HIGH - bus_name##_ADDRESS_LOW)
#endif
#ifndef SOC_DRAM1_CACHE_ADDRESS_HIGH
#define SOC_DRAM1_CACHE_ADDRESS_HIGH 0x3FC00000
#endif
#ifndef SOC_DRAM1_CACHE_ADDRESS_LOW
#define SOC_DRAM1_CACHE_ADDRESS_LOW 0x3F800000
#endif
#ifndef SOC_DRAM_FLASH_ADDRESS_HIGH
#define SOC_DRAM_FLASH_ADDRESS_HIGH SOC_DROM0_CACHE_ADDRESS_HIGH
#endif
#ifndef SOC_DRAM_FLASH_ADDRESS_LOW
#define SOC_DRAM_FLASH_ADDRESS_LOW SOC_DROM0_CACHE_ADDRESS_LOW
#endif
#ifndef SOC_DROM0_CACHE_ADDRESS_HIGH
#define SOC_DROM0_CACHE_ADDRESS_HIGH 0x3F800000
#endif
#ifndef SOC_DROM0_CACHE_ADDRESS_LOW
#define SOC_DROM0_CACHE_ADDRESS_LOW 0x3F400000
#endif
#ifndef SOC_IRAM0_CACHE_ADDRESS_HIGH
#define SOC_IRAM0_CACHE_ADDRESS_HIGH 0x40400000
#endif
#ifndef SOC_IRAM0_CACHE_ADDRESS_LOW
#define SOC_IRAM0_CACHE_ADDRESS_LOW 0x400D0000
#endif
#ifndef SOC_IRAM1_CACHE_ADDRESS_HIGH
#define SOC_IRAM1_CACHE_ADDRESS_HIGH 0x40800000
#endif
#ifndef SOC_IRAM1_CACHE_ADDRESS_LOW
#define SOC_IRAM1_CACHE_ADDRESS_LOW 0x40400000
#endif
#ifndef SOC_IRAM_FLASH_ADDRESS_HIGH
#define SOC_IRAM_FLASH_ADDRESS_HIGH SOC_IRAM0_CACHE_ADDRESS_HIGH
#endif
#ifndef SOC_IRAM_FLASH_ADDRESS_LOW
#define SOC_IRAM_FLASH_ADDRESS_LOW SOC_IRAM0_CACHE_ADDRESS_LOW
#endif
#ifndef SOC_IROM0_CACHE_ADDRESS_HIGH
#define SOC_IROM0_CACHE_ADDRESS_HIGH 0x40C00000
#endif
#ifndef SOC_IROM0_CACHE_ADDRESS_LOW
#define SOC_IROM0_CACHE_ADDRESS_LOW 0x40800000
#endif
#ifndef SOC_MMU_DBUS_VADDR_BASE
#define SOC_MMU_DBUS_VADDR_BASE 0x3E000000
#endif
#ifndef SOC_MMU_DRAM1_LINEAR_ADDRESS_HIGH
#define SOC_MMU_DRAM1_LINEAR_ADDRESS_HIGH (SOC_DRAM1_CACHE_ADDRESS_HIGH & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_DRAM1_LINEAR_ADDRESS_LOW
#define SOC_MMU_DRAM1_LINEAR_ADDRESS_LOW (SOC_DRAM1_CACHE_ADDRESS_LOW & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_DROM0_LINEAR_ADDRESS_HIGH
#define SOC_MMU_DROM0_LINEAR_ADDRESS_HIGH (SOC_DROM0_CACHE_ADDRESS_HIGH & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_DROM0_LINEAR_ADDRESS_LOW
#define SOC_MMU_DROM0_LINEAR_ADDRESS_LOW (SOC_DROM0_CACHE_ADDRESS_LOW & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_ENTRY_NUM
#define SOC_MMU_ENTRY_NUM 384
#endif
#ifndef SOC_MMU_IBUS_VADDR_BASE
#define SOC_MMU_IBUS_VADDR_BASE 0x40000000
#endif
#ifndef SOC_MMU_INVALID
#define SOC_MMU_INVALID BIT(8)
#endif
#ifndef SOC_MMU_IRAM0_LINEAR_ADDRESS_HIGH
#define SOC_MMU_IRAM0_LINEAR_ADDRESS_HIGH (SOC_IRAM0_CACHE_ADDRESS_HIGH & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_IRAM0_LINEAR_ADDRESS_LOW
#define SOC_MMU_IRAM0_LINEAR_ADDRESS_LOW (SOC_IRAM0_CACHE_ADDRESS_LOW & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_IRAM1_LINEAR_ADDRESS_HIGH
#define SOC_MMU_IRAM1_LINEAR_ADDRESS_HIGH (SOC_IRAM1_CACHE_ADDRESS_HIGH & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_IRAM1_LINEAR_ADDRESS_LOW
#define SOC_MMU_IRAM1_LINEAR_ADDRESS_LOW (SOC_IRAM1_CACHE_ADDRESS_LOW & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_IROM0_LINEAR_ADDRESS_HIGH
#define SOC_MMU_IROM0_LINEAR_ADDRESS_HIGH (SOC_IROM0_CACHE_ADDRESS_HIGH & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_IROM0_LINEAR_ADDRESS_LOW
#define SOC_MMU_IROM0_LINEAR_ADDRESS_LOW (SOC_IROM0_CACHE_ADDRESS_LOW & SOC_MMU_LINEAR_ADDR_MASK)
#endif
#ifndef SOC_MMU_LINEAR_ADDR_MASK
#define SOC_MMU_LINEAR_ADDR_MASK 0x1FFFFFF
#endif
#ifndef SOC_MMU_MAX_PADDR_PAGE_NUM
#define SOC_MMU_MAX_PADDR_PAGE_NUM 256
#endif
#ifndef SOC_MMU_VADDR_MASK
#define SOC_MMU_VADDR_MASK 0x3FFFFF
#endif

/* --- Enums (implicit values backfilled; ABI attrs preserved) --- */

/* --- Structs & Typedefs (merged, source order preserved for C forward refs) --- */



#ifdef __cplusplus
}
#endif
#endif /* __WINK_HARVESTED_SOC_EXT_MEM_DEFS_H__ */
#endif /* _CACHE_MEMORY_H_ */
