/* SPDX-License-Identifier: LGPL-3.0-only */
/* Harvested from esp-idf v6.1@fff9895c (Apache-2.0) — factual C-ABI only, comments stripped. See NOTICE. */
/* AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY! Manifest: 542eb37a5dc3604c Source: v6.1@fff9895c Config: esp32/v6.1 */
#ifndef WINK_H_GUARD_SOC_INTERRUPTS_H
#define WINK_H_GUARD_SOC_INTERRUPTS_H
#ifndef __WINK_HARVESTED_SOC_INTERRUPTS_H__
#define __WINK_HARVESTED_SOC_INTERRUPTS_H__
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "wink_sla.h"
#include <stdint.h>


#ifdef __cplusplus
extern "C" {
#endif
/* --- Macros (object + allowlisted function-like; first-wins + #ifndef wrapped) --- */
#ifndef ETS_CAN_INTR_SOURCE
#define ETS_CAN_INTR_SOURCE ETS_TWAI_INTR_SOURCE
#endif

/* --- Enums (implicit values backfilled; ABI attrs preserved) --- */
typedef enum {
    ETS_WIFI_MAC_INTR_SOURCE = 0,
    ETS_WIFI_MAC_NMI_SOURCE = 1,
    ETS_WIFI_BB_INTR_SOURCE = 2,
    ETS_BT_MAC_INTR_SOURCE = 3,
    ETS_BT_BB_INTR_SOURCE = 4,
    ETS_BT_BB_NMI_SOURCE = 5,
    ETS_RWBT_INTR_SOURCE = 6,
    ETS_RWBLE_INTR_SOURCE = 7,
    ETS_RWBT_NMI_SOURCE = 8,
    ETS_RWBLE_NMI_SOURCE = 9,
    ETS_SLC0_INTR_SOURCE = 10,
    ETS_SLC1_INTR_SOURCE = 11,
    ETS_UHCI0_INTR_SOURCE = 12,
    ETS_UHCI1_INTR_SOURCE = 13,
    ETS_TG0_T0_LEVEL_INTR_SOURCE = 14,
    ETS_TG0_T1_LEVEL_INTR_SOURCE = 15,
    ETS_TG0_WDT_LEVEL_INTR_SOURCE = 16,
    ETS_TG0_LACT_LEVEL_INTR_SOURCE = 17,
    ETS_TG1_T0_LEVEL_INTR_SOURCE = 18,
    ETS_TG1_T1_LEVEL_INTR_SOURCE = 19,
    ETS_TG1_WDT_LEVEL_INTR_SOURCE = 20,
    ETS_TG1_LACT_LEVEL_INTR_SOURCE = 21,
    ETS_GPIO_INTR_SOURCE = 22,
    ETS_GPIO_NMI_SOURCE = 23,
    ETS_FROM_CPU_INTR0_SOURCE = 24,
    ETS_FROM_CPU_INTR1_SOURCE = 25,
    ETS_FROM_CPU_INTR2_SOURCE = 26,
    ETS_FROM_CPU_INTR3_SOURCE = 27,
    ETS_SPI0_INTR_SOURCE = 28,
    ETS_SPI1_INTR_SOURCE = 29,
    ETS_SPI2_INTR_SOURCE = 30,
    ETS_SPI3_INTR_SOURCE = 31,
    ETS_I2S0_INTR_SOURCE = 32,
    ETS_I2S1_INTR_SOURCE = 33,
    ETS_UART0_INTR_SOURCE = 34,
    ETS_UART1_INTR_SOURCE = 35,
    ETS_UART2_INTR_SOURCE = 36,
    ETS_SDIO_HOST_INTR_SOURCE = 37,
    ETS_ETH_MAC_INTR_SOURCE = 38,
    ETS_PWM0_INTR_SOURCE = 39,
    ETS_PWM1_INTR_SOURCE = 40,
    ETS_LEDC_INTR_SOURCE = 43,
    ETS_EFUSE_INTR_SOURCE = 44,
    ETS_TWAI_INTR_SOURCE = 45,
    ETS_RTC_CORE_INTR_SOURCE = 46,
    ETS_RMT_INTR_SOURCE = 47,
    ETS_PCNT_INTR_SOURCE = 48,
    ETS_I2C_EXT0_INTR_SOURCE = 49,
    ETS_I2C_EXT1_INTR_SOURCE = 50,
    ETS_RSA_INTR_SOURCE = 51,
    ETS_SPI1_DMA_INTR_SOURCE = 52,
    ETS_SPI2_DMA_INTR_SOURCE = 53,
    ETS_SPI3_DMA_INTR_SOURCE = 54,
    ETS_WDT_INTR_SOURCE = 55,
    ETS_TIMER1_INTR_SOURCE = 56,
    ETS_TIMER2_INTR_SOURCE = 57,
    ETS_TG0_T0_EDGE_INTR_SOURCE = 58,
    ETS_TG0_T1_EDGE_INTR_SOURCE = 59,
    ETS_TG0_WDT_EDGE_INTR_SOURCE = 60,
    ETS_TG0_LACT_EDGE_INTR_SOURCE = 61,
    ETS_TG1_T0_EDGE_INTR_SOURCE = 62,
    ETS_TG1_T1_EDGE_INTR_SOURCE = 63,
    ETS_TG1_WDT_EDGE_INTR_SOURCE = 64,
    ETS_TG1_LACT_EDGE_INTR_SOURCE = 65,
    ETS_MMU_IA_INTR_SOURCE = 66,
    ETS_MPU_IA_INTR_SOURCE = 67,
    ETS_CACHE_IA_INTR_SOURCE = 68,
    ETS_MAX_INTR_SOURCE = 69,
} periph_interrupt_t;

/* --- Structs & Typedefs (merged, source order preserved for C forward refs) --- */



#ifdef __cplusplus
}
#endif
#endif /* __WINK_HARVESTED_SOC_INTERRUPTS_H__ */
#endif /* WINK_H_GUARD_SOC_INTERRUPTS_H */
