# THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
# wink-micro-os/tools/codegen/tests/golden_multi_device.json.
# Do not edit manually — changes will be overwritten on next build.

set(WINK_USE_LED ON CACHE BOOL "" FORCE)
set(WINK_USE_BUTTON OFF CACHE BOOL "" FORCE)
set(WINK_USE_SERVO ON CACHE BOOL "" FORCE)
set(WINK_USE_SSD1306 ON CACHE BOOL "" FORCE)
set(WINK_USE_ULTRASONIC OFF CACHE BOOL "" FORCE)
set(WINK_USE_GPS OFF CACHE BOOL "" FORCE)
set(WINK_USE_EEPROM OFF CACHE BOOL "" FORCE)
set(WINK_USE_MOTOR OFF CACHE BOOL "" FORCE)
set(WINK_USE_ENCODER OFF CACHE BOOL "" FORCE)

# Calculate WINK_MAX_PERIODIC (sum of instance counts + 4)
set(WINK_MAX_PERIODIC 6 CACHE STRING "" FORCE)
