/*
 * THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_multi_device.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#define LOG_TAG "device_tree"

#include "device_tree.h"
#include "wink_fault.h"
#include "wink_actuator_registry.h"
#ifdef WINK_PT_DEBUG
#include "wink_pt_debug.h"
#include "wink_tasks.h"
#endif
#include "hal/pal_i2c.h"
#include "pal_log.h"

/* ── Static device instances (zero malloc) ── */
dal_led_t status_led = {0};
dal_servo_t neck_servo = {0};
dal_ssd1306_t display = {0};

/* ── Actuator safe-off thunks ── */
WINK_DEFINE_ACTUATOR_THUNK(status_led_safe_off, dal_led_off, dal_led_t)
WINK_DEFINE_ACTUATOR_THUNK(neck_servo_safe_off, dal_servo_safe_off, dal_servo_t)

/* ── Init sequence ── */
wink_status_t wink_device_tree_init(void)
{
    /* ── Shared bus initializations ── */
    WINK_TRY(pal_i2c_bus_init(0, 21, 22, 100000));

    /* status_led (led, actuator) */
    static const dal_led_config_t status_led_cfg = {
        .owner = "status_led",
        .pin = 2,
        .active_high = true,
    };
    WINK_TRY(dal_led_init(&status_led, &status_led_cfg));

    /* neck_servo (servo, actuator) */
    static const dal_servo_config_t neck_servo_cfg = {
        .owner = "neck_servo",
        .pwm_channel = 0,
        .min_pulse_ms = 0.5f,
        .max_pulse_ms = 2.5f,
    };
    WINK_TRY(dal_servo_init(&neck_servo, &neck_servo_cfg));

    /* display (ssd1306) */
    static const dal_ssd1306_config_t display_cfg = {
        .i2c_port = 0,
        .i2c_addr = 0x3C,
        .width = 128,
        .height = 64,
        .owner = "display",
    };
    WINK_TRY(dal_ssd1306_init(&display, &display_cfg));

    /* ── After all device inits succeed, register actuator safe-off (reverse order) ── */
    WINK_TRY(wink_actuator_register(neck_servo_safe_off, &neck_servo));
    WINK_TRY(wink_actuator_register(status_led_safe_off, &status_led));

    return WINK_OK;
}

/* ── Deinit sequence (init reversed) ── */
void wink_device_tree_deinit(void)
{
    /* Unregister actuators first (forward init order = reverse of register order). */
    WINK_IGNORE_RESULT(wink_actuator_unregister(status_led_safe_off, &status_led));
    WINK_IGNORE_RESULT(wink_actuator_unregister(neck_servo_safe_off, &neck_servo));

    WINK_IGNORE_RESULT(dal_ssd1306_deinit(&display));
    WINK_IGNORE_RESULT(dal_servo_deinit(&neck_servo));
    WINK_IGNORE_RESULT(dal_led_deinit(&status_led));

    /* ── Shared bus deinitializations (reverse order) ── */
    pal_i2c_bus_deinit(0);
#ifdef WINK_PT_DEBUG
    WINK_ASSERT(wink_periodic_active_count() == 0);
#endif
}
