/*
 * THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_multi_device.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#ifndef WINK_ARDUINO_BINDINGS_H
#define WINK_ARDUINO_BINDINGS_H

#include "WinkUltrasonic.h"
#include "WinkServo.h"

#ifdef __cplusplus
extern WinkServo arduino_neck_servo;
#define neck_servo arduino_neck_servo
#endif

#endif /* WINK_ARDUINO_BINDINGS_H */
