/*
 * THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_multi_device.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#include "wink_arduino_bindings.h"
#include "device_tree.h"

#ifdef __cplusplus
WinkServo arduino_neck_servo(neck_servo);
#endif
