# THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
# tests/golden_devkitc.json.
# Do not edit manually — changes will be overwritten on next build.

set(WINK_USE_LED ON CACHE BOOL "" FORCE)
set(WINK_USE_BUTTON ON CACHE BOOL "" FORCE)
set(WINK_USE_ULTRASONIC ON CACHE BOOL "" FORCE)

# Calculate WINK_MAX_PERIODIC (sum of instance counts + 4)
set(WINK_MAX_PERIODIC 7 CACHE STRING "" FORCE)
