# THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
# tools/codegen/tests/golden_devkitc.json.
# Do not edit manually — changes will be overwritten on next build.

set(WINK_USE_LED ON CACHE BOOL "" FORCE)
set(WINK_USE_BUTTON ON CACHE BOOL "" FORCE)
set(WINK_USE_SERVO OFF CACHE BOOL "" FORCE)
set(WINK_USE_SSD1306 OFF CACHE BOOL "" FORCE)
set(WINK_USE_ULTRASONIC ON CACHE BOOL "" FORCE)
set(WINK_USE_GPS OFF CACHE BOOL "" FORCE)
set(WINK_USE_EEPROM OFF CACHE BOOL "" FORCE)
set(WINK_USE_MOTOR OFF CACHE BOOL "" FORCE)
set(WINK_USE_ENCODER OFF CACHE BOOL "" FORCE)

# Calculate WINK_MAX_PERIODIC (sum of instance counts + 4)
set(WINK_MAX_PERIODIC 7 CACHE STRING "" FORCE)
