/*
 * THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
 * wink-micro-os/tools/codegen/tests/golden_devkitc.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#ifndef DEVICE_TREE_H
#define DEVICE_TREE_H

#include "dal_led.h"
#include "dal_button.h"
#include "dal_ultrasonic.h"
#include "input/wink_button_events.h"
#include "sensor/wink_ultrasonic_distance_events.h"
#include "wink_status.h"

/* ── Instance count macros (slots allocation) ── */
#define WINK_APP_MAX_LED_INSTANCES 1u
#define WINK_APP_MAX_BUTTON_INSTANCES 1u
#define WINK_APP_MAX_ULTRASONIC_INSTANCES 1u
#define WINK_APP_MAX_SERVO_INSTANCES 0u

/* ── Driver configuration constants ── */
#define BOARD_LED_ACTIVE_HIGH true
#define BOOT_BUTTON_AUTO_POLL_MS 10u
#define BOOT_BUTTON_LONG_PRESS_MS 3000u
#define BOOT_BUTTON_DEBOUNCE_MS 20u
#define BOOT_BUTTON_EVENT_DRIVE_SOFT_POLL true
#define SMOKE_ULTRASONIC_USE_RMT true
#define SMOKE_ULTRASONIC_AUTO_POLL_MS 50u

#ifdef __cplusplus
extern "C" {
#endif

/* ── Device instance handles (extern; business code accesses by name) ── */
extern dal_led_t board_led;
extern dal_button_t boot_button;
extern dal_ultrasonic_t smoke_ultrasonic;

/* ── Role-based instance APIs (static inline) ── */
static inline void board_led_activate(void) { WINK_IGNORE_RESULT(dal_led_on(&board_led)); }
static inline void board_led_deactivate(void) { WINK_IGNORE_RESULT(dal_led_off(&board_led)); }
static inline void board_led_toggle(void) { WINK_IGNORE_RESULT(dal_led_toggle(&board_led)); }
static inline bool boot_button_is_active(void) { bool p = false; WINK_IGNORE_RESULT(dal_button_is_pressed(&boot_button, &p)); return p; }
WINK_WARN_UNUSED_RESULT static inline wink_status_t boot_button_is_active_status(bool *out_active) { return dal_button_is_pressed(&boot_button, out_active); }
static inline bool boot_button_was_active(void) { bool p = false; WINK_IGNORE_RESULT(dal_button_was_pressed(&boot_button, &p)); return p; }
WINK_WARN_UNUSED_RESULT static inline wink_status_t boot_button_was_active_status(bool *out_pressed) { return dal_button_was_pressed(&boot_button, out_pressed); }
WINK_WARN_UNUSED_RESULT static inline wink_status_t boot_button_enable_events(void) { static const wink_button_event_config_t cfg = { .drive = WINK_BUTTON_DRIVE_SOFT_POLL, .auto_poll_ms = 10u, .debounce_ms = 20u, .wake_from_sleep = false }; return wink_button_enable_events(&boot_button, &cfg); }
static inline void boot_button_disable_events(void) { wink_button_disable_events(&boot_button); }
WINK_WARN_UNUSED_RESULT static inline wink_status_t boot_button_start_auto_poll(uint32_t poll_ms) { const wink_button_event_config_t cfg = { .drive = WINK_BUTTON_DRIVE_SOFT_POLL, .auto_poll_ms = poll_ms, .debounce_ms = BOOT_BUTTON_DEBOUNCE_MS, .wake_from_sleep = false }; return wink_button_enable_events(&boot_button, &cfg); }
static inline void boot_button_stop_auto_poll(void) { wink_button_disable_events(&boot_button); }
WINK_WARN_UNUSED_RESULT static inline wink_status_t smoke_ultrasonic_request_measurement(void) { return dal_ultrasonic_request_measurement(&smoke_ultrasonic); }
static inline float smoke_ultrasonic_read_distance(void) { float d = -1.0f; WINK_IGNORE_RESULT(dal_ultrasonic_get_cached_distance(&smoke_ultrasonic, &d)); return d; }
WINK_WARN_UNUSED_RESULT static inline wink_status_t smoke_ultrasonic_read_distance_status(float *out_dist_cm) { return dal_ultrasonic_get_cached_distance(&smoke_ultrasonic, out_dist_cm); }
WINK_WARN_UNUSED_RESULT static inline wink_status_t smoke_ultrasonic_enable_distance_events(void) { static const wink_ultrasonic_distance_event_config_t cfg = { .period_ms = 50u }; return wink_ultrasonic_enable_distance_events(&smoke_ultrasonic, &cfg); }
static inline void smoke_ultrasonic_disable_distance_events(void) { wink_ultrasonic_disable_distance_events(&smoke_ultrasonic); }

/* ── Device tree lifecycle ── */

/**
 * @brief Initialise all static devices and register actuator safe-off hooks.
 *
 * Init order follows JSON declaration order (with depends_on honoured).
 * Actuator safe-off callbacks are registered only after every device init
 * has succeeded, so the registry never sees a half-initialised device.
 *
 * @return WINK_OK on full success; otherwise the first failing status.
 */
WINK_WARN_UNUSED_RESULT
wink_status_t wink_device_tree_init(void);

/**
 * @brief De-initialise all devices in reverse init order.
 *
 * Actuators are unregistered first (in forward init order — the inverse of
 * the reverse-order register list — so the stack discipline matches). Then
 * device deinits run in reverse init order. Safe to call from a partially
 * initialised state: un-inited handles are no-ops.
 */
void wink_device_tree_deinit(void);

#ifdef __cplusplus
}
#endif
#endif /* DEVICE_TREE_H */
