/*
 * THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_devkitc.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#define LOG_TAG "device_tree"

#include "device_tree.h"
#include "wink_fault.h"
#include "wink_actuator_registry.h"
#ifdef WINK_PT_DEBUG
#include "wink_pt_debug.h"
#include "wink_tasks.h"
#endif
#include "pal_log.h"

/* ── Static device instances (zero malloc) ── */
dal_led_t board_led = {0};
dal_button_t boot_button = {0};
dal_ultrasonic_t smoke_ultrasonic = {0};

/* ── Actuator safe-off thunks ── */
WINK_DEFINE_ACTUATOR_THUNK(board_led_safe_off, dal_led_off, dal_led_t)

/* ── Init sequence ── */
wink_status_t wink_device_tree_init(void)
{
    /* board_led (led, actuator) */
    static const dal_led_config_t board_led_cfg = {
        .owner = "board_led",
        .pin = 2,
        .active_high = true,
    };
    WINK_TRY(dal_led_init(&board_led, &board_led_cfg));

    /* boot_button (button) */
    static const dal_button_config_t boot_button_cfg = {
        .owner = "boot_button",
        .pin = 0,
        .active_low = true,
    };
    WINK_TRY(dal_button_init(&boot_button, &boot_button_cfg));
    WINK_TRY(dal_button_set_long_press_ms(&boot_button, 3000));
    WINK_TRY(dal_button_enable_isr_counter(&boot_button));

    /* smoke_ultrasonic (ultrasonic) */
    static const dal_ultrasonic_config_t smoke_ultrasonic_cfg = {
        .owner = "smoke_ultrasonic",
        .trig_pin = 18,
        .echo_pin = 19,
        .use_rmt = true,
    };
    WINK_TRY(dal_ultrasonic_init(&smoke_ultrasonic, &smoke_ultrasonic_cfg));

    /* ── After all device inits succeed, register actuator safe-off (reverse order) ── */
    WINK_TRY(wink_actuator_register(board_led_safe_off, &board_led));

    return WINK_OK;
}

/* ── Deinit sequence (init reversed) ── */
void wink_device_tree_deinit(void)
{
    /* Unregister actuators first (forward init order = reverse of register order). */
    WINK_IGNORE_RESULT(wink_actuator_unregister(board_led_safe_off, &board_led));

    WINK_IGNORE_RESULT(dal_ultrasonic_deinit(&smoke_ultrasonic));
    WINK_IGNORE_RESULT(dal_button_deinit(&boot_button));
    WINK_IGNORE_RESULT(dal_led_deinit(&board_led));
#ifdef WINK_PT_DEBUG
    WINK_ASSERT(wink_periodic_active_count() == 0);
#endif
}
