/*
 * THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_devkitc.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#ifndef WINK_ARDUINO_BINDINGS_H
#define WINK_ARDUINO_BINDINGS_H

#include "WinkUltrasonic.h"
#include "WinkServo.h"

#ifdef __cplusplus
extern WinkUltrasonic arduino_smoke_ultrasonic;
#define smoke_ultrasonic arduino_smoke_ultrasonic
#endif

#endif /* WINK_ARDUINO_BINDINGS_H */
