/*
 * THIS FILE IS AUTOGENERATED by wink-micro-os/tools/codegen/app_codegen.py from
 * wink-micro-os/tools/codegen/tests/golden_devkitc.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#include "wink_arduino_bindings.h"
#include "device_tree.h"

#ifdef __cplusplus
WinkUltrasonic arduino_smoke_ultrasonic(smoke_ultrasonic);
#endif
