/*
 * THIS FILE IS AUTOGENERATED by tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_multi_device.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#ifndef DEVICE_TREE_H
#define DEVICE_TREE_H

#include "dal_led.h"
#include "dal_servo.h"
#include "dal_ssd1306.h"
#include "wink_status.h"

/* ── Instance count macros (slots allocation) ── */
#define WINK_APP_MAX_LED_INSTANCES 1u
#define WINK_APP_MAX_BUTTON_INSTANCES 0u
#define WINK_APP_MAX_ULTRASONIC_INSTANCES 0u
#define WINK_APP_MAX_SERVO_INSTANCES 1u

/* ── Driver configuration constants ── */
#define STATUS_LED_ACTIVE_HIGH true
#define NECK_SERVO_MIN_PULSE_MS 0.5f
#define NECK_SERVO_MAX_PULSE_MS 2.5f
#define DISPLAY_I2C_ADDR 0x3C

#ifdef __cplusplus
extern "C" {
#endif

/* ── Device instance handles (extern; business code accesses by name) ── */
extern dal_led_t status_led;
extern dal_servo_t neck_servo;
extern dal_ssd1306_t display;

/* ── Device tree lifecycle ── */

/**
 * @brief Initialise all static devices and register actuator safe-off hooks.
 *
 * Init order follows JSON declaration order (with depends_on honoured).
 * Actuator safe-off callbacks are registered only after every device init
 * has succeeded, so the registry never sees a half-initialised device.
 *
 * @return WINK_OK on full success; otherwise the first failing status.
 */
WINK_WARN_UNUSED_RESULT
wink_status_t wink_device_tree_init(void);

/**
 * @brief De-initialise all devices in reverse init order.
 *
 * Actuators are unregistered first (in forward init order — the inverse of
 * the reverse-order register list — so the stack discipline matches). Then
 * device deinits run in reverse init order. Safe to call from a partially
 * initialised state: un-inited handles are no-ops.
 */
void wink_device_tree_deinit(void);

#ifdef __cplusplus
}
#endif
#endif /* DEVICE_TREE_H */
