#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
mcs51_sdcc_devhdr.py — transpile the vendor Keil device header (cms8s78xx.h)
into an SDCC-compatible device header for the Tier-S compile gate (GAP-03).

The gate must compile unmodified user sources with a *real* 8051 C compiler.
Hand-maintained placeholder SFR tables would drift from silicon the same way
the C++ shim did (cf. GAP-01/22), so this tool mechanically converts the
vendor header fixtures:

  sfr NAME = 0xNN;                 -> __sfr __at(0xNN) NAME;
  sbit NAME = REG^b;               -> __sbit __at(base+b) NAME;
  #define N *(... xdata *)0xNNNN   -> __xdata volatile unsigned char
                                     __at(0xNNNN) N;
  Keil stdint typedefs             -> dropped (<stdint.h> on the include path)
  trailing comma in vendor enum   -> removed (SDCC rejects it)

The SFR name->address table collected here is also the source of truth for
mcs51_cleanup.py's `sbit N = REG^b;` rewrite on the SDCC target.

Usage:
    python mcs51_sdcc_devhdr.py VENDOR_HEADER OUTPUT_HEADER
"""
import re
import sys

# Vendor header uses absolute sbit addresses for some aliases; relative forms
# reference exactly the SFR names declared by `sfr`.
SFR_RE = re.compile(r'\bsfr\s+([A-Za-z0-9_]+)\s*=\s*0x([0-9A-Fa-f]+)\s*;')
SBIT_RE = re.compile(r'\bsbit\s+([A-Za-z0-9_]+)\s*=\s*([A-Za-z0-9_]+)\s*\^\s*(\d+)\s*;')
XSFR_RE = re.compile(
    r'#define\s+([A-Za-z0-9_]+)\s*\*\(\s*volatile\s+unsigned\s+char\s+xdata\s*\*\)\s*0x([0-9A-Fa-f]{4})')


def transpile(text: str) -> tuple[str, dict]:
    sfr_addr: dict[str, int] = {}
    unresolved_sbits: list[str] = []

    # Drop only the Keil integer typedefs (stdint provides them); keep
    # typedef enums/structs intact.
    text = "\n".join(line for line in text.splitlines()
                     if not re.match(r'\s*typedef\s+(signed|unsigned)\b', line))

    def sfr_sub(m):
        sfr_addr[m.group(1)] = int(m.group(2), 16)
        return f"__sfr __at(0x{m.group(2)}) {m.group(1)};"

    text = SFR_RE.sub(sfr_sub, text)

    def sbit_sub(m):
        name, reg, bit = m.group(1), m.group(2), int(m.group(3))
        base = sfr_addr.get(reg)
        if base is None:
            unresolved_sbits.append(name)
            return f"/* unresolved sbit {name} = {reg}^{bit} */"
        return f"__sbit __at(0x{base + bit:02X}) {name};"

    text = SBIT_RE.sub(sbit_sub, text)

    def xsfr_sub(m):
        return (f"__xdata volatile unsigned char __at(0x{m.group(2)}) "
                f"{m.group(1)};")

    text = XSFR_RE.sub(xsfr_sub, text)

    # SDCC rejects a trailing comma in the vendor en_Priority_Module enum.
    text = re.sub(r',(\s*\}\s*en_Priority_Module_t)', r'\1', text)

    header = [
        "/* AUTO-GENERATED by mcs51_sdcc_devhdr.py — DO NOT EDIT. "
        "Transpiled from the vendor cms8s78xx.h for the SDCC compile gate. */",
        "#ifndef CMS8S78XX_SDCC_DEVHDR_H",
        "#define CMS8S78XX_SDCC_DEVHDR_H",
        "#include <stdint.h>",
        "typedef unsigned char bit;",
        "",
        text,
        "#endif",
    ]
    stats = {"sfr": len(sfr_addr),
             "unresolved_sbit": unresolved_sbits}
    return "\n".join(header), stats


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src = open(argv[1], encoding="utf-8", errors="replace").read()
    out, stats = transpile(src)
    open(argv[2], "w", encoding="utf-8", newline="\n").write(out)
    print(f"sfrs: {stats['sfr']}, unresolved sbits: "
          f"{stats['unresolved_sbit'] or 'none'}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
