// [AUTO-GENERATED by @wink-ai/unisim-ui/generator. DO NOT EDIT MANUALLY.]
// Source: wokwi-servo
import type { PinsOverlayMap } from '@wink-ai/unisim-ui';

export const RC_SERVO_AUTOGEN_SIZE = Object.freeze({
  width: 171,
  height: 120,
});

export const RC_SERVO_AUTOGEN_OVERLAY: Readonly<PinsOverlayMap> = Object.freeze({
  "GND": Object.freeze({
    relX: 0,
    relY: 50,
    wireNet: 'gnd' as const,
    defaultConnection: 'GND' as const,
    required: false,
  }),
  "VCC": Object.freeze({
    relX: 0,
    relY: 60,
    wireNet: 'vcc' as const,
    defaultConnection: 'VCC' as const,
    required: false,
  }),
  "PWM": Object.freeze({
    relX: 0,
    relY: 69,
    wireNet: 'primary' as const,
    defaultConnection: null,
    required: true,
  }),
});
