/**
 * @file app_callbacks.c
 * @brief DevKitC smoke-test firmware (P0-1 slim): device tree centralized,
 *        app only wires helpers + selftest.
 *
 * Init / deinit boilerplate for LED / button / ultrasonic lives in
 * device_tree.c. This TU only:
 *   - defines business event callbacks (long-press → WDT test)
 *   - kicks off helper services (blink, sim echo, telemetry, sonar polling)
 *   - invokes the OS built-in selftest suite
 *
 * Verifies on bare metal (no wiring required):
 *   S1  2s telemetry                (BAL: wink_telemetry_default_start)
 *   S2  LED blink                    (common: wink_led_blink_start)
 *   S3  Boot-button debounce         (DAL: dal_button_poll)
 *   S4  GPIO ISR edge count          (DAL: dal_button_enable_isr_counter)
 *   S5  PWM router freq isolation    (selftest: pwm_router.freq_isolation)
 *   S6  I2C bus scan (no-panic)      (selftest: i2c.bus_scan)
 *   S7  Dual-core resource stress    (selftest: smp.resource_stress)
 *   S8  WDT reset via long-press     (Runtime: wink_runtime_trigger_wdt_test)
 *   S9  RMT hardware loopback        (selftest: rmt.self_loopback)
 *   S10 Ultrasonic echo simulation   (common: wink_sim_ultrasonic_echo_start)
 */
#define LOG_TAG "devkitc_smoke"

#include "device_tree.h"
#include "wink_app.h"
#include "wink_runtime.h"
#include "wink_selftest.h"
#include "wink_fault.h"
#include "wink_blink_helper.h"
#include "wink_telemetry_helper.h"
#include "wink_sim_ultrasonic_echo.h"
#include "pal_log.h"

/* Generated by codegen (see wink-app.json / app_support.c) — starts BAL
 * services (currently just wink_button_helper for boot_button auto-poll). */
extern wink_status_t wink_app_services_start(void);

/* ADR-0017 layer-1 exception: app init legitimately calls WINK_BLOCKING APIs
 * (selftest i2c_scan/rmt_wait sleep, ultrasonic request_measurement). */
#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

/* ── S8: Boot-button event callback (long-press → WDT test, noreturn) ───── */
static void on_boot_button(dal_button_event_t evt, void *ctx)
{
    (void)ctx;
    if (evt == DAL_BUTTON_EVT_LONG_PRESS) {
        LOG_I("S8: long-press detected, arming WDT test");
        wink_runtime_trigger_wdt_test(2000); /* does not return */
    }
}

/* ── S8: Boot notification (Runtime fires this once before init()) ──────── */
static void app_on_boot(const wink_boot_info_t *info)
{
    if (info->abnormal_boot_count > 0 ||
        info->reset_reason == WINK_RESET_REASON_WATCHDOG) {
        LOG_I("watchdog: PASS (recovered after abnormal reset, count=%lu, reason=%d)",
              (unsigned long)info->abnormal_boot_count, (int)info->reset_reason);
    }
}

/* ── S10: periodic ultrasonic measurement (runs in its own task) ────────── */
static void sonar_poll_task(void *ctx)
{
    WINK_IGNORE_RESULT(dal_ultrasonic_request_measurement((dal_ultrasonic_t *)ctx));
}

/* ── init: hand off device init to device_tree, then wire helpers + selftest ─ */
static void app_init(void)
{
    /* 设备树初始化（集中 init/register，返回首个错误即 fault） */
    WINK_CHECK(wink_device_tree_init(), WINK_FAULT_APP(0));

    /* 启动 codegen 生成的 BAL 服务（当前：boot_button 10ms auto-poll） */
    WINK_CHECK(wink_app_services_start(), WINK_FAULT_APP(1));

    /* 绑定业务回调（传感器事件回调是业务层关注点） */
    WINK_IGNORE_RESULT(dal_button_on_event(&boot_button, on_boot_button, NULL));

    /* S2: LED blink helper（fire-and-forget） */
    wink_led_blink_start(&board_led, 1000);

    /* S10: 超声波 echo 仿真 + 周期测量任务。引脚号来自设备实例自身的 config
     * 副本（dal_ultrasonic.h 公开字段），避免在 device_tree.h 里再暴露引脚宏。 */
    WINK_IGNORE_RESULT(wink_sim_ultrasonic_echo_start(
        &smoke_sonar, 50.0f,
        smoke_sonar.config.trig_pin, smoke_sonar.config.echo_pin));
    WINK_IGNORE_RESULT(wink_runtime_spawn_periodic(
        "sonar_poll", 2048, 500, sonar_poll_task, &smoke_sonar, 1, PAL_OS_CORE_ANY));

    /* S1: 默认遥测（BAL helper, MAY_BLOCK 路径） */
    WINK_IGNORE_RESULT(wink_telemetry_default_start(&smoke_sonar, &boot_button));

    /* ── S5/S6/S7/S9/S4-isr: OS built-in selftest (one call).
     *    selftest_core already logs PASS/SKIP/FAIL per entry; we only need to
     *    raise a fault if anything hard-failed (UNSUPPORTED = skip ≠ fail). */
    wink_selftest_result_t results[8];
    size_t n = 0;
    WINK_IGNORE_RESULT(wink_selftest_run("*", results, 8, &n));
    for (size_t i = 0; i < n; i++) {
        if (results[i].status != WINK_OK &&
            results[i].status != WINK_ERR_UNSUPPORTED) {
            LOG_E("%s: FAIL (metric=%lu)", results[i].name,
                  (unsigned long)results[i].metric);
            wink_trace_fault(WINK_FAULT_APP(2));
        }
    }

    LOG_I("init done. Long-press BOOT (>3s) to trigger WDT reset test.");
}

/* ── loop (10ms tick): empty. button_helper auto-polls; sonar_poll_task
 *    handles periodic ultrasonic; other work is background tasks. Keeping
 *    the callback (rather than deleting) preserves the runtime heartbeat. */
static void app_loop(void)
{
    /* no-op — see comment above */
}

/* ── Fault callback (Runtime already ran safe-off-all before this) ─────── */
static void app_on_fault(uint32_t code)
{
    (void)code;
}

/* ── Callback factory (binary decoupling) ──────────────────────────────── */
const wink_app_callbacks_t *wink_app_get_callbacks(void)
{
    static const wink_app_callbacks_t cb = {
        .init     = app_init,
        .loop     = app_loop,
        .on_fault = app_on_fault,
        .on_boot  = app_on_boot,
    };
    return &cb;
}
