// [AUTO-GENERATED by @wink-ai/unisim-ui/generator. DO NOT EDIT MANUALLY.]
// Source: wokwi-hc-sr04
import type { PinsOverlayMap } from '@wink-ai/unisim-ui';

export const ULTRASONIC_AUTOGEN_SIZE = Object.freeze({
  width: 171,
  height: 95,
});

export const ULTRASONIC_AUTOGEN_OVERLAY: Readonly<PinsOverlayMap> = Object.freeze({
  VCC: Object.freeze({
    relX: 71,
    relY: 95,
    wireNet: 'vcc' as const,
    defaultConnection: 'VCC' as const,
    required: false,
  }),
  TRIG: Object.freeze({
    relX: 81,
    relY: 95,
    wireNet: 'primary' as const,
    defaultConnection: null,
    required: true,
  }),
  ECHO: Object.freeze({
    relX: 91,
    relY: 95,
    wireNet: 'secondary' as const,
    defaultConnection: null,
    required: false,
  }),
  GND: Object.freeze({
    relX: 101,
    relY: 95,
    wireNet: 'gnd' as const,
    defaultConnection: 'GND' as const,
    required: false,
  }),
});
