// [AUTO-GENERATED by @wink-ai/unisim-ui/generator. DO NOT EDIT MANUALLY.]
// Source: wokwi-led
import type { PinsOverlayMap } from '@wink-ai/unisim-ui';

export const LED_AUTOGEN_SIZE = Object.freeze({
  width: 40,
  height: 50,
});

export const LED_AUTOGEN_OVERLAY: Readonly<PinsOverlayMap> = Object.freeze({
  A: Object.freeze({
    relX: 24,
    relY: 42,
    wireNet: 'primary' as const,
    defaultConnection: null,
    required: true,
  }),
  C: Object.freeze({
    relX: 16,
    relY: 42,
    wireNet: 'gnd' as const,
    defaultConnection: 'GND' as const,
    required: false,
  }),
});
