/*
 * THIS FILE IS AUTOGENERATED by tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_devkitc.json.
 * Do not edit manually — changes will be overwritten on next build.
 *
 * app_support.c hosts codegen-owned glue between the device tree and the
 * hand-written app_callbacks.c: forward declarations of user callbacks and
 * ``wink_app_services_start()`` — the entry point invoked after device tree
 * init to spin up BAL helpers (button polling, telemetry, …).
 */
#include "device_tree.h"
#include "wink_status.h"
#include "wink_fault.h"
#include "wink_button_helper.h"

/**
 * @brief Start all app-level services (button polling, telemetry, sim helpers).
 *
 * Called by the runtime after ``wink_device_tree_init()`` succeeds. Returns
 * the first failure status; the caller escalates to a fault so partially
 * started services are torn down by the runtime's safe-off flow.
 */
wink_status_t wink_app_services_start(void)
{
    WINK_TRY(wink_button_helper_start(&boot_button, 10));
    return WINK_OK;
}
