/*
 * THIS FILE IS AUTOGENERATED by tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_devkitc.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#ifndef DEVICE_TREE_H
#define DEVICE_TREE_H

#include "dal_led.h"
#include "dal_button.h"
#include "dal_ultrasonic.h"
#include "wink_button_helper.h"
#include "wink_status.h"

/* ── Instance count macros (slots allocation) ── */
#define WINK_APP_MAX_LED_INSTANCES 1u
#define WINK_APP_MAX_BUTTON_INSTANCES 1u
#define WINK_APP_MAX_ULTRASONIC_INSTANCES 1u
#define WINK_APP_MAX_SERVO_INSTANCES 0u

/* ── Driver configuration constants ── */
#define BOARD_LED_ACTIVE_HIGH true
#define BOOT_BUTTON_AUTO_POLL_MS 10u
#define BOOT_BUTTON_LONG_PRESS_MS 3000u
#define SMOKE_SONAR_USE_RMT true

#ifdef __cplusplus
extern "C" {
#endif

/* ── Device instance handles (extern; business code accesses by name) ── */
extern dal_led_t board_led;
extern dal_button_t boot_button;
extern dal_ultrasonic_t smoke_sonar;

/* ── Role-based instance APIs (static inline) ── */
static inline void board_led_activate(void) { WINK_IGNORE_RESULT(dal_led_on(&board_led)); }
static inline void board_led_deactivate(void) { WINK_IGNORE_RESULT(dal_led_off(&board_led)); }
static inline void board_led_toggle(void) { WINK_IGNORE_RESULT(dal_led_toggle(&board_led)); }
static inline bool boot_button_is_active(void) { bool p = false; WINK_IGNORE_RESULT(dal_button_is_pressed(&boot_button, &p)); return p; }
WINK_WARN_UNUSED_RESULT static inline wink_status_t boot_button_is_active_status(bool *out_active) { return dal_button_is_pressed(&boot_button, out_active); }
static inline bool boot_button_was_active(void) { bool p = false; WINK_IGNORE_RESULT(dal_button_was_pressed(&boot_button, &p)); return p; }
WINK_WARN_UNUSED_RESULT static inline wink_status_t boot_button_was_active_status(bool *out_pressed) { return dal_button_was_pressed(&boot_button, out_pressed); }
WINK_WARN_UNUSED_RESULT static inline wink_status_t boot_button_start_auto_poll(uint32_t poll_ms) { return wink_button_helper_start(&boot_button, poll_ms); }
static inline void boot_button_stop_auto_poll(void) { wink_button_helper_stop(&boot_button); }
WINK_WARN_UNUSED_RESULT static inline wink_status_t smoke_sonar_request_measurement(void) { return dal_ultrasonic_request_measurement(&smoke_sonar); }
static inline float smoke_sonar_read_distance(void) { float d = -1.0f; WINK_IGNORE_RESULT(dal_ultrasonic_get_cached_distance(&smoke_sonar, &d)); return d; }
WINK_WARN_UNUSED_RESULT static inline wink_status_t smoke_sonar_read_distance_status(float *out_dist_cm) { return dal_ultrasonic_get_cached_distance(&smoke_sonar, out_dist_cm); }

/* ── Device tree lifecycle ── */

/**
 * @brief Initialise all static devices and register actuator safe-off hooks.
 *
 * Init order follows JSON declaration order (with depends_on honoured).
 * Actuator safe-off callbacks are registered only after every device init
 * has succeeded, so the registry never sees a half-initialised device.
 *
 * @return WINK_OK on full success; otherwise the first failing status.
 */
WINK_WARN_UNUSED_RESULT
wink_status_t wink_device_tree_init(void);

/**
 * @brief De-initialise all devices in reverse init order.
 *
 * Actuators are unregistered first (in forward init order — the inverse of
 * the reverse-order register list — so the stack discipline matches). Then
 * device deinits run in reverse init order. Safe to call from a partially
 * initialised state: un-inited handles are no-ops.
 */
void wink_device_tree_deinit(void);

#ifdef __cplusplus
}
#endif
#endif /* DEVICE_TREE_H */
