/*
 * THIS FILE IS AUTOGENERATED by tools/codegen/app_codegen.py from
 * tools/codegen/tests/golden_devkitc.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#ifndef DEVICE_TREE_H
#define DEVICE_TREE_H

#include "dal_led.h"
#include "dal_button.h"
#include "dal_ultrasonic.h"
#include "wink_status.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ── Device instance handles (extern; business code accesses by name) ── */
extern dal_led_t board_led;
extern dal_button_t boot_button;
extern dal_ultrasonic_t smoke_sonar;

/* ── Device tree lifecycle ── */

/**
 * @brief Initialise all static devices and register actuator safe-off hooks.
 *
 * Init order follows JSON declaration order (with depends_on honoured).
 * Actuator safe-off callbacks are registered only after every device init
 * has succeeded, so the registry never sees a half-initialised device.
 *
 * @return WINK_OK on full success; otherwise the first failing status.
 */
WINK_WARN_UNUSED_RESULT
wink_status_t wink_device_tree_init(void);

/**
 * @brief De-initialise all devices in reverse init order.
 *
 * Actuators are unregistered first (in forward init order — the inverse of
 * the reverse-order register list — so the stack discipline matches). Then
 * device deinits run in reverse init order. Safe to call from a partially
 * initialised state: un-inited handles are no-ops.
 */
void wink_device_tree_deinit(void);

#ifdef __cplusplus
}
#endif
#endif /* DEVICE_TREE_H */
