# THIS FILE IS AUTOGENERATED by wink-tools/tools/codegen/app_codegen.py from
# D:/MyWorkSpace_program/lowcode-nocode/ai-app/wink-ai-embedded/wink-micro-app/dual_task_demo/wink-app.json.
# Do not edit manually — changes will be overwritten on next build.

set(WINK_USE_ANALOG_KNOB OFF CACHE BOOL "" FORCE)
set(WINK_USE_BUTTON OFF CACHE BOOL "" FORCE)
set(WINK_USE_BUZZER OFF CACHE BOOL "" FORCE)
set(WINK_USE_DC_MOTOR OFF CACHE BOOL "" FORCE)
set(WINK_USE_EEPROM OFF CACHE BOOL "" FORCE)
set(WINK_USE_ENCODER OFF CACHE BOOL "" FORCE)
set(WINK_USE_GPS OFF CACHE BOOL "" FORCE)
set(WINK_USE_KEYPAD OFF CACHE BOOL "" FORCE)
set(WINK_USE_LED OFF CACHE BOOL "" FORCE)
set(WINK_USE_MONO_OLED OFF CACHE BOOL "" FORCE)
set(WINK_USE_RC_SERVO ON CACHE BOOL "" FORCE)
set(WINK_USE_RELAY OFF CACHE BOOL "" FORCE)
set(WINK_USE_ULTRASONIC ON CACHE BOOL "" FORCE)

# Calculate WINK_MAX_PERIODIC (sum of instance counts + 4)
set(WINK_MAX_PERIODIC 6 CACHE STRING "" FORCE)
