#!/usr/bin/env python3
"""List DAL drivers from the codegen registry (ADR-0046 SSOT).

Emits CMake data tables, JSON inventories, or consistency checks.
Generated CMake is data-only: consumers foreach WINK_KNOWN_DRIVERS and call
their own enable helpers (never emit _wink_dal_enable* calls here).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable, List, Sequence

# Allow `python list_drivers.py` from tools/codegen/ and package imports.
_CODEGEN_DIR = Path(__file__).resolve().parent
_SDK_ROOT = _CODEGEN_DIR.parent.parent  # wink-micro-os/
if str(_SDK_ROOT) not in sys.path:
    sys.path.insert(0, str(_SDK_ROOT))

from tools.codegen.drivers import all_drivers  # noqa: E402
from tools.codegen.drivers.base import DriverBase  # noqa: E402


def _sorted_drivers() -> List[DriverBase]:
    return sorted(all_drivers(), key=lambda d: d.type)


def _type_token(drv: DriverBase) -> str:
    return drv.type.upper()


def render_cmake(mode: str) -> str:
    if mode not in ("source", "defs"):
        raise ValueError(f"mode must be 'source' or 'defs', got {mode!r}")

    drivers = _sorted_drivers()
    lines: List[str] = [
        "# AUTO-GENERATED by tools/codegen/list_drivers.py — DO NOT EDIT.",
        "# Edit tools/codegen/drivers/<type>.py instead (ADR-0046).",
        f"# mode={mode}",
        "",
    ]

    tokens = [_type_token(d) for d in drivers]
    lines.append(f"set(WINK_KNOWN_DRIVERS {' '.join(tokens)})")
    lines.append("")

    for drv in drivers:
        tok = _type_token(drv)
        cat = drv.resolved_category()
        stem = drv.resolved_stem()
        lines.append(f"set(WINK_DAL_{tok}_CATEGORY {cat})")
        lines.append(f"set(WINK_DAL_{tok}_STEM {stem})")
        lines.append(f"set(WINK_DAL_{tok}_REL_SRC {drv.rel_src()})")
    lines.append("")

    for drv in drivers:
        tok = _type_token(drv)
        pretty = drv.type.replace("_", " ").title()
        lines.append(f'option(WINK_USE_{tok} "Enable DAL {pretty} driver" ON)')
    lines.append("")

    # Extras must run only after the caller sets WINK_DAL_TARGET (not at include time).
    lines.append("# Apply multi-TU / sub-option fragments; caller must set(WINK_DAL_TARGET ...).")
    lines.append("function(wink_dal_apply_extra_cmake)")
    lines.append('  if(NOT WINK_DAL_TARGET)')
    lines.append(
        '    message(FATAL_ERROR "wink_dal_apply_extra_cmake: WINK_DAL_TARGET is not set")'
    )
    lines.append("  endif()")

    any_extra = False
    for drv in drivers:
        tok = _type_token(drv)
        defs = (drv.extra_cmake_defs or "").rstrip()
        sources = (drv.extra_cmake_sources or "").rstrip()
        if not defs and not (mode == "source" and sources):
            continue
        any_extra = True
        lines.append(f"  if(WINK_USE_{tok})")
        if defs:
            lines.append(
                f"    # ── extra_cmake_defs from drivers/{drv.type}.py ──"
            )
            for raw in defs.splitlines():
                lines.append(f"    {raw}" if raw.strip() else "")
        if mode == "source" and sources:
            lines.append(
                f"    # ── extra_cmake_sources from drivers/{drv.type}.py ──"
            )
            for raw in sources.splitlines():
                lines.append(f"    {raw}" if raw.strip() else "")
        lines.append("  endif()")

    if not any_extra:
        lines.append("  # (no drivers declare extra_cmake_*)")
    lines.append("endfunction()")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_json() -> str:
    payload = []
    for drv in _sorted_drivers():
        payload.append(
            {
                "type": drv.type,
                "category": drv.resolved_category(),
                "source_stem": drv.resolved_stem(),
                "is_actuator": bool(drv.is_actuator),
                "has_extra_cmake_sources": bool(drv.extra_cmake_sources.strip()),
                "has_extra_cmake_defs": bool(drv.extra_cmake_defs.strip()),
            }
        )
    return json.dumps(payload, indent=2) + "\n"


def _primary_dal_stems(sdk_root: Path) -> set[str]:
    """Basenames of primary dal_<stem>.c files (exclude font/internal TUs)."""
    stems: set[str] = set()
    src_root = sdk_root / "dal" / "src"
    if not src_root.is_dir():
        return stems
    for path in src_root.rglob("dal_*.c"):
        name = path.stem  # dal_led / dal_ssd1306_font_5x7_minimal
        if "_font_" in name or name.endswith("_internal"):
            continue
        if not name.startswith("dal_"):
            continue
        stems.add(name[len("dal_") :])
    return stems


def check_consistency(sdk_root: Path | None = None) -> List[str]:
    """Return human-readable error strings (empty == OK)."""
    root = sdk_root or _SDK_ROOT
    errors: List[str] = []
    drivers = _sorted_drivers()
    registered_stems = {d.resolved_stem() for d in drivers}

    for drv in drivers:
        hdr = root / drv.rel_hdr()
        src = root / drv.rel_src()
        if not hdr.is_file():
            errors.append(f"missing header for type={drv.type!r}: {drv.rel_hdr()}")
        if not src.is_file():
            errors.append(f"missing source for type={drv.type!r}: {drv.rel_src()}")

    for stem in sorted(_primary_dal_stems(root)):
        if stem not in registered_stems:
            errors.append(
                f"orphan DAL source stem {stem!r} has no codegen driver plugin"
            )

    return errors


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--cmake",
        action="store_true",
        help="Emit generated_drivers.cmake data to stdout",
    )
    group.add_argument(
        "--json",
        action="store_true",
        help="Emit driver inventory JSON to stdout",
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="Verify registry ↔ dal sources; exit 1 on errors",
    )
    parser.add_argument(
        "--mode",
        choices=("source", "defs"),
        default="source",
        help="CMake emission mode (default: source)",
    )
    parser.add_argument(
        "--sdk-root",
        type=Path,
        default=None,
        help="Override wink-micro-os root for --check",
    )
    args = parser.parse_args(argv)

    if args.cmake:
        sys.stdout.write(render_cmake(args.mode))
        return 0
    if args.json:
        sys.stdout.write(render_json())
        return 0

    errs = check_consistency(args.sdk_root)
    if errs:
        for e in errs:
            print(f"error: {e}", file=sys.stderr)
        return 1
    print("list_drivers --check: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
