<#
.SYNOPSIS
    切换 ESP32 firmware 到 SMP UAF 验证测试。
.DESCRIPTION
    自动更新 app_sources.cmake 指向 samples/smp_uaf_test/。
    运行后执行 idf.py build flash monitor 即可烧录测试。
#>

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AppSourcesFile = Join-Path $ScriptDir "main\app_sources.cmake"

$Content = @'
# ============================================================
# AUTO-GENERATED by switch_to_smp_uaf_test.ps1 - DO NOT EDIT MANUALLY
# ============================================================
# App Name: smp_uaf_test
# Generated at: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# ============================================================

set(WINK_APP_NAME "smp_uaf_test" CACHE STRING "Current samples app name" FORCE)
set(WINK_APP_DIR "${CMAKE_CURRENT_LIST_DIR}/../../wink-micro-os/samples/smp_uaf_test" CACHE PATH "Current samples app directory" FORCE)

set(WINK_APP_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/../../wink-micro-os/samples/smp_uaf_test/app_callbacks.c
    ${CMAKE_CURRENT_LIST_DIR}/../../wink-micro-os/samples/smp_uaf_test/device_tree.c
    ${CMAKE_CURRENT_LIST_DIR}/../../wink-micro-os/samples/smp_uaf_test/test_smp_uaf.c
    CACHE INTERNAL "Auto-scanned source files from samples/smp_uaf_test"
)

message(STATUS "[WINK App Auto-Scan] App = smp_uaf_test, source files = 3")
'@

$Content | Out-File -FilePath $AppSourcesFile -Encoding utf8

Write-Host "✅ 已切换到 SMP UAF 验证测试" -ForegroundColor Green
Write-Host ""
Write-Host "📋 下一步操作：" -ForegroundColor Cyan
Write-Host "   cd esp32_firmware"
Write-Host "   idf.py build flash monitor"
Write-Host ""
Write-Host "💡 验证步骤：" -ForegroundColor Yellow
Write-Host "   1. 第一次运行：启用 synchronize() → 应该 100% 通过"
Write-Host "   2. 修改 app_callbacks.c，设置 TEST_ENABLE_SYNCHRONIZE=false"
Write-Host "   3. 重新编译运行：几十轮内会触发 UAF，证明 synchronize 必要"
Write-Host ""
