#!/usr/bin/env python3
"""App (Application Layer) C code generator for WinkMicroOS.

This tool generates State Struct pattern C code for business logic,
enforcing the safety rules from ADR-0011:
1. All persistent state is stored in WINK_PT_STATE struct
2. NO static local variables in protothread functions
3. Task ID prefixes ensure namespace isolation

Usage:
    python app_codegen.py --input my_app.json --output generated/app_main.c
"""
import json
import argparse
import os
import sys
from typing import Dict, List, Any


def generate_state_struct(task_name: str, task_id: int, variables: List[Dict[str, str]]) -> str:
    """Generate WINK_PT_STATE_BEGIN/END block with task-prefixed variables.

    Args:
        task_name: Name of the task (for struct naming)
        task_id: Unique numeric ID for namespace isolation
        variables: List of {name, type, comment} dicts

    Returns:
        String containing the state struct definition
    """
    members = []
    for var in variables:
        var_name = var['name']
        var_type = var['type']
        comment = var.get('comment', '')
        comment_str = f"  // {comment}" if comment else ''
        members.append(
            f"    {var_type} task_{task_id:03d}_{var_name};{comment_str}"
        )

    members_str = '\n'.join(members)

    return f"""\
// ============================================================
//  State Struct for task: {task_name}
//  Auto-generated by app_codegen.py - DO NOT EDIT MANUALLY
//  Task ID prefix: task_{task_id:03d}_
// ============================================================
WINK_PT_STATE_BEGIN({task_name})
{members_str}
WINK_PT_STATE_END()
"""


def generate_globals(task_name: str) -> str:
    """Generate global control block and state instance declarations.

    Args:
        task_name: Name of the task

    Returns:
        String containing global declarations
    """
    return f"""\
// Global state context (owned by runtime, supports multi-instance)
static struct {task_name}_state g_{task_name}_state;
static wink_pt_t g_{task_name}_pt;
"""


def generate_init_function(task_name: str, task_id: int, init_steps: List[str]) -> str:
    """Generate app_init function with State Struct initialization.

    Args:
        task_name: Name of the task
        task_id: Unique task ID
        init_steps: List of C code statements for initialization

    Returns:
        String containing app_init function
    """
    init_body = '\n    '.join(init_steps) if init_steps else ''

    return f"""\
/**
 * @brief Initialize application state and peripherals
 * Auto-generated by app_codegen.py
 */
void app_init(void) {{
    // Initialize protothread control block and state struct
    WINK_PT_INIT(&g_{task_name}_pt);
    memset(&g_{task_name}_state, 0, sizeof(g_{task_name}_state));
    g_{task_name}_state._magic = 0x50545354UL;  // PTST magic marker

    {init_body}
}}
"""


def generate_loop_function(task_name: str, task_id: int, loop_body: str,
                          tick_rate_ms: int = 10) -> str:
    """Generate app_loop function with full State Struct pattern.

    Args:
        task_name: Name of the task
        task_id: Unique task ID
        loop_body: C code for the main loop body (inside while(1))
        tick_rate_ms: Tick delay in milliseconds

    Returns:
        String containing app_loop function
    """
    return f"""\
/**
 * @brief Main business logic loop (protothread pattern)
 * Auto-generated by app_codegen.py - State Struct mode enforced
 *
 * SAFETY GUARANTEES (ADR-0011):
 * - All persistent state accessed via state-> pointer
 * - NO stack variables survive WINK_PT_DELAY_MS/yield
 * - Multi-instance safe: g_{task_name}_state can be instantiated N times
 * - State is serializable for: Web debugging, sleep/wake, crash dumps
 */
void app_loop(void) {{
    // Inject state pointer (compile-time constant, zero runtime cost)
    WINK_PT_STATE_USE({task_name});

    // Protothread entry point - resumes here after yield
    WINK_PT_BEGIN(&g_{task_name}_pt);

    while (1) {{
        {loop_body}

        // Yield control back to scheduler
        // WARNING: All stack variables become UNDEFINED after this point!
        // All persistent state MUST be in state-> before yielding.
        WINK_PT_DELAY_MS(&g_{task_name}_pt, {tick_rate_ms});
    }}

    WINK_PT_END(&g_{task_name}_pt);
}}
"""


def generate_fault_handler(fault_actions: List[str]) -> str:
    """Generate app_on_fault handler.

    Args:
        fault_actions: List of C code statements for fault handling

    Returns:
        String containing app_on_fault function
    """
    actions_body = '\n    '.join(fault_actions) if fault_actions else ''

    return f"""\
/**
 * @brief Fault handling callback
 * Auto-generated by app_codegen.py
 */
void app_on_fault(uint32_t fault_code) {{
    // Safety: fault handler should only perform minimal, safe actions
    // NEVER block, NEVER allocate, NEVER use protothreads here.
    {actions_body}
    wink_trace_fault(fault_code);
}}
"""


def generate_full_app(config: Dict[str, Any]) -> str:
    """Generate complete App code from JSON config.

    Args:
        config: Parsed JSON configuration with:
            - task_name: Name of the application task
            - task_id: Unique numeric ID
            - includes: List of header files to include
            - state_variables: List of {name, type, comment}
            - init_steps: List of C statements for init
            - loop_body: C code for main loop
            - tick_rate_ms: Tick rate in ms
            - fault_actions: List of C statements for fault handler

    Returns:
        Complete C code as string
    """
    task_name = config.get('task_name', 'app_main')
    task_id = config.get('task_id', 1)
    includes = config.get('includes', ['device_tree.h', 'app_config.h', 'wink_app.h'])
    variables = config.get('state_variables', [])
    init_steps = config.get('init_steps', [])
    loop_body = config.get('loop_body', '// Add your business logic here')
    tick_rate_ms = config.get('tick_rate_ms', 10)
    fault_actions = config.get('fault_actions', [])

    # Build includes
    include_lines = '\n'.join([f'#include "{inc}"' for inc in includes])

    # Build components
    state_struct = generate_state_struct(task_name, task_id, variables)
    globals_decl = generate_globals(task_name)
    init_func = generate_init_function(task_name, task_id, init_steps)
    loop_func = generate_loop_function(task_name, task_id, loop_body, tick_rate_ms)
    fault_func = generate_fault_handler(fault_actions)

    # Assemble full file
    return f"""\
/**
 * @file {task_name}.c
 * @brief Auto-generated App (Application Layer) code
 *
 * THIS FILE IS AUTO-GENERATED BY app_codegen.py - DO NOT EDIT MANUALLY!
 *
 * Design Pattern: State Struct (ADR-0011 Compliance)
 * - All persistent state in wink_pt_t-derived struct
 * - NO static local variables in protothread context
 * - Multi-instance safe, serialization-ready
 *
 * Task: {task_name}
 * Task ID Prefix: task_{task_id:03d}_
 */

// ============================================================
//  Includes
// ============================================================
{include_lines}
#include <string.h>  // for memset

// ============================================================
//  State Definition
// ============================================================
{state_struct}
// ============================================================
//  Global Contexts
// ============================================================
{globals_decl}
// ============================================================
//  Init Function
// ============================================================
{init_func}
// ============================================================
//  Main Loop (Protothread)
// ============================================================
{loop_func}
// ============================================================
//  Fault Handler
// ============================================================
{fault_func}
"""


def main():
    parser = argparse.ArgumentParser(
        description="App C Code Generator (State Struct pattern)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example JSON input:
{
    "task_name": "obstacle_avoidance",
    "task_id": 1,
    "includes": ["device_tree.h", "app_config.h", "wink_app.h"],
    "state_variables": [
        {"name": "current_state", "type": "system_state_t", "comment": "State machine state"},
        {"name": "last_distance", "type": "float", "comment": "Last radar reading"}
    ],
    "init_steps": ["dal_led_set_state(&status_led, LED_STATE_OFF);"],
    "loop_body": "float distance = 0.0f;\\n        wink_status_t status = dal_ultrasonic_get_cached_distance(&front_radar, &distance);\\n        if (status == WINK_ERR_BUSY) {\\n            // Measurement in progress, wait for next tick\\n        } else {\\n            // Start new measurement for next cycle\\n            dal_ultrasonic_request_measurement(&front_radar);\\n            // Process distance...\\n        }",
    "tick_rate_ms": 10,
    "fault_actions": ["(void)dal_servo_set_angle(&neck_servo, 90.0f);"]
}
        """
    )
    parser.add_argument('--input', help='Path to App configuration JSON (required unless --example)')
    parser.add_argument('--output', help='Path to output C file (required unless --example)')
    parser.add_argument('--example', action='store_true', help='Print example JSON config')
    args = parser.parse_args()

    if args.example:
        example = {
            "task_name": "obstacle_avoidance",
            "task_id": 1,
            "includes": ["device_tree.h", "app_config.h", "wink_app.h"],
            "state_variables": [
                {"name": "current_state", "type": "system_state_t", "comment": "State machine state"},
                {"name": "last_distance", "type": "float", "comment": "Last radar reading"},
                {"name": "scan_tick", "type": "uint32_t", "comment": "Last scan timestamp"}
            ],
            "init_steps": [
                "dal_led_set_state(&status_led, LED_STATE_OFF);",
                "dal_servo_set_angle(&neck_servo, 90.0f);"
            ],
            "loop_body": """float distance = 0.0f;
        wink_status_t status = dal_ultrasonic_get_cached_distance(&front_radar, &distance);
        if (status == WINK_OK) {
            state->task_001_last_distance = distance;
            if (distance < 20.0f) {
                state->task_001_current_state = SYSTEM_STATE_AVOIDING;
            }
        } else if (status == WINK_ERR_BUSY) {
            // Measurement still in progress, wait a tick
        } else {
            // Try to trigger new measurement for next cycle
            dal_ultrasonic_request_measurement(&front_radar);
        }""",
            "tick_rate_ms": 10,
            "fault_actions": [
                "(void)dal_servo_set_angle(&neck_servo, 90.0f);",
                "(void)dal_led_set_state(&status_led, LED_STATE_ON);"
            ]
        }
        print(json.dumps(example, indent=4))
        return 0

    # Check required arguments
    if not args.input or not args.output:
        print("[ERROR] --input and --output are required unless using --example", file=sys.stderr)
        parser.print_help()
        return 1

    # Load configuration
    try:
        with open(args.input, 'r', encoding='utf-8') as f:
            config = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"[ERROR] Failed to load config: {e}", file=sys.stderr)
        return 1

    # Generate code
    code = generate_full_app(config)

    # Ensure output directory exists
    output_dir = os.path.dirname(args.output)
    if output_dir:  # Only create if directory is specified (not current dir)
        os.makedirs(output_dir, exist_ok=True)

    # Write output
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(code)

    print(f"[OK] Generated App code: {args.output}")
    print(f"     Task: {config.get('task_name', 'app_main')}")
    print(f"     State variables: {len(config.get('state_variables', []))}")
    print(f"     Tick rate: {config.get('tick_rate_ms', 10)}ms")
    return 0


if __name__ == '__main__':
    sys.exit(main())
