/*
 * SPDX-License-Identifier: Apache-2.0
 * THIS FILE IS AUTOGENERATED by wink-tools/tools/codegen/app_codegen.py from
 * D:/MyWorkSpace_program/lowcode-nocode/ai-app/wink-ai-embedded/wink-micro-app/unisim_smoke/wink-app.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#ifndef WINK_ARDUINO_BINDINGS_H
#define WINK_ARDUINO_BINDINGS_H

#include "WinkUltrasonic.h"
#include "WinkRcServo.h"

#ifdef __cplusplus
extern WinkUltrasonic arduino_us_sensor;
#define us_sensor arduino_us_sensor
#endif

#endif /* WINK_ARDUINO_BINDINGS_H */
