/*
 * SPDX-License-Identifier: Apache-2.0
 * THIS FILE IS AUTOGENERATED by wink-tools/tools/codegen/app_codegen.py from
 * D:/MyWorkSpace_program/lowcode-nocode/ai-app/wink-ai-embedded/wink-micro-app/unisim_smoke/wink-app.json.
 * Do not edit manually — changes will be overwritten on next build.
 */
#include "wink_arduino_bindings.h"
#include "device_tree.h"

#ifdef __cplusplus
WinkUltrasonic arduino_us_sensor(us_sensor);
#endif
