// SPDX-License-Identifier: Apache-2.0
/**
 * @file test_dal_ntc.c
 * @brief DAL NTC thermistor driver unit tests (host Unity).
 */
#ifndef WINK_USE_NTC
#define WINK_USE_NTC 1
#endif

#if defined(_MSC_VER)
/* WINK_BLOCKING marks blocking read APIs as deprecated; host tests call them directly. */
#  pragma warning(push)
#  pragma warning(disable: 4996)
#endif

#include "unity.h"
#include "wink_status.h"
#include "sensor/dal_ntc.h"
#include "hal/pal_adc.h"
#include "pal_resource.h"
#include "host_test_ctrl.h"

static const char *const OWNER = "test_dal_ntc";
#define TEST_PIN 36
#define TEST_VREF_MV 3300u

/* 33-entry x 0.1 degC, 10k/B3950/10k pull-up (generated by ntc_lut_gen.py).
 * raw=2048 (idx 16) -> 250 = 25.0 degC. */
static const int16_t s_lut_10k_3950_10k[33] = {
     3000, 1293, 1016,  866,  763,  685,  621,  567,
      520,  477,  439,  403,  369,  338,  308,  278,
      250,  222,  194,  167,  139,  111,   82,   53,
       22,  -12,  -47,  -87, -132, -186, -257, -365, -500,
};

/* 33-entry x 0.1 degC, 100k/B3950/4.7k pull-up (generated).
 * raw=128 (idx 0) -> 3000 = 300.0 degC, used for over-temp cutoff. */
static const int16_t s_lut_100k_3950_4k7[33] = {
     3000, 3000, 2547, 2254, 2059, 1913, 1796, 1698,
     1613, 1537, 1469, 1407, 1349, 1294, 1242, 1193,
     1144, 1097, 1051, 1005,  959,  913,  866,  818,
      767,  714,  657,  594,  523,  438,  330,  166, -500,
};

void setUp(void) {
    pal_resource_reset();
    for (uint8_t i = 0; i < PAL_ADC_CHANNELS; i++) {
        pal_adc_deinit(i);
    }
}

void tearDown(void) {}

static dal_ntc_config_t base_cfg(const int16_t *lut) {
    dal_ntc_config_t cfg = {
        .owner = OWNER,
        .r25_ohm = 10000,
        .r_pull_ohm = 10000,
        .variant = DAL_NTC_VARIANT_SINGLE_ENDED_ADC,
        .divider_type = DAL_NTC_DIVIDER_PULL_UP,
        .ao_pin = TEST_PIN,
        .diff_neg_pin = WINK_PIN_NC,
        .b_value = 3950,
        .vref_mv = TEST_VREF_MV,
        .min_valid_temp_c = -30,
        .max_valid_temp_c = 280,
        .debounce_count = 3,
        .lut_table = lut,
    };
    return cfg;
}

static pal_adc_channel_t init_and_get_channel(dal_ntc_t *dev, const dal_ntc_config_t *cfg) {
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_init(dev, cfg));
    pal_adc_channel_t ch = 0;
    TEST_ASSERT_EQUAL_INT(WINK_OK, pal_adc_pin_channel(TEST_PIN, &ch));
    return ch;
}

void test_ntc_init_success_and_claim(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_init(&dev, &cfg));
    TEST_ASSERT_TRUE(dev.initialized);
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_get_last_status(&dev));

    /* Resources are held: a second claim on the same pin must be rejected. */
    TEST_ASSERT_EQUAL_INT(WINK_ERR_BUSY,
        pal_resource_claim(PAL_RESOURCE_GPIO_PIN, TEST_PIN, "intruder"));

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
}

void test_ntc_init_resource_collision(void) {
    dal_ntc_t a = {0};
    dal_ntc_t b = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_init(&a, &cfg));
    /* Second instance on the same ADC pin with a different owner must be
     * rejected by resource arbitration; first instance stays intact. */
    dal_ntc_config_t cfg2 = cfg;
    cfg2.owner = "test_dal_ntc_intruder";
    wink_status_t st = dal_ntc_init(&b, &cfg2);
    TEST_ASSERT_TRUE(st == WINK_ERR_BUSY || st == WINK_ERR_RESOURCE_EXHAUSTED);
    TEST_ASSERT_TRUE(a.initialized);
    TEST_ASSERT_FALSE(b.initialized);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&a));
}

void test_ntc_deinit_release(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_init(&dev, &cfg));
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
    TEST_ASSERT_FALSE(dev.initialized);

    /* After release, the same pin can be claimed again. */
    dal_ntc_t dev2 = {0};
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_init(&dev2, &cfg));
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev2));
}

void test_ntc_read_degc_b_curve_accuracy(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);
    pal_adc_channel_t ch = init_and_get_channel(&dev, &cfg);

    /* 25 degC: R=10k, divider midpoint -> raw 2048 */
    pal_host_adc_inject_raw(ch, 2048);
    float t = 0.0f;
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_read_degc(&dev, &t));
    TEST_ASSERT_FLOAT_WITHIN(0.5f, 25.0f, t);

    /* 100 degC: R~696 ohm, ratio ~0.0651 -> raw ~267 */
    pal_host_adc_inject_raw(ch, 267);
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_read_degc(&dev, &t));
    TEST_ASSERT_FLOAT_WITHIN(1.0f, 100.0f, t);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
}

void test_ntc_lut_interpolation(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);
    pal_adc_channel_t ch = init_and_get_channel(&dev, &cfg);

    /* raw 2048 -> idx16 frac0 -> exact node 250 (25.0 degC) */
    pal_host_adc_inject_raw(ch, 2048);
    int16_t ddegc = 0;
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_read_ddegc(&dev, &ddegc));
    TEST_ASSERT_EQUAL_INT16(250, ddegc);

    /* raw 2112 -> idx16 frac64 -> 250 + (222-250)*64/128 = 236 (23.6 degC) */
    pal_host_adc_inject_raw(ch, 2112);
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_read_ddegc(&dev, &ddegc));
    TEST_ASSERT_EQUAL_INT16(236, ddegc);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
}

void test_ntc_read_ddegc_null_lut_returns_invalid_state(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(NULL);

    pal_adc_channel_t ch = init_and_get_channel(&dev, &cfg);
    pal_host_adc_inject_raw(ch, 2048);

    int16_t ddegc = 0;
    TEST_ASSERT_EQUAL_INT(WINK_ERR_INVALID_STATE, dal_ntc_read_ddegc(&dev, &ddegc));

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
}

void test_ntc_open_circuit_debounce(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);
    cfg.debounce_count = 3;
    pal_adc_channel_t ch = init_and_get_channel(&dev, &cfg);

    /* raw 4095 -> V_sig ~ Vref -> open circuit (pull-up) */
    pal_host_adc_inject_raw(ch, 4095);
    int16_t ddegc = 0;
    TEST_ASSERT_EQUAL_INT(WINK_ERR_BUSY, dal_ntc_read_ddegc(&dev, &ddegc));
    TEST_ASSERT_EQUAL_INT(WINK_ERR_BUSY, dal_ntc_read_ddegc(&dev, &ddegc));
    TEST_ASSERT_EQUAL_INT(WINK_ERR_HARDWARE, dal_ntc_read_ddegc(&dev, &ddegc));
    TEST_ASSERT_TRUE(dev.fault_open);
    TEST_ASSERT_FALSE(dev.fault_short);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
}

void test_ntc_short_circuit_pull_down(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);
    cfg.divider_type = DAL_NTC_DIVIDER_PULL_DOWN;
    cfg.debounce_count = 0;  /* immediate latch */
    pal_adc_channel_t ch = init_and_get_channel(&dev, &cfg);

    /* Pull-down: V_sig ~ Vref means NTC ~ 0 -> short */
    pal_host_adc_inject_raw(ch, 4095);
    int16_t ddegc = 0;
    TEST_ASSERT_EQUAL_INT(WINK_ERR_HARDWARE, dal_ntc_read_ddegc(&dev, &ddegc));
    TEST_ASSERT_TRUE(dev.fault_short);
    TEST_ASSERT_FALSE(dev.fault_open);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
}

void test_ntc_differential_unsupported(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);
    cfg.variant = DAL_NTC_VARIANT_DIFFERENTIAL_BRIDGE;

    TEST_ASSERT_EQUAL_INT(WINK_ERR_UNSUPPORTED, dal_ntc_init(&dev, &cfg));
}

void test_ntc_overtemperature_cutoff(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_100k_3950_4k7);
    cfg.r25_ohm = 100000;
    cfg.r_pull_ohm = 4700;
    cfg.max_valid_temp_c = 280;
    pal_adc_channel_t ch = init_and_get_channel(&dev, &cfg);

    /* raw 128 -> LUT node 0 = 300.0 degC > 280 -> over-temperature.
     * mV ~103 stays above the short deadband so it is not a hard fault. */
    pal_host_adc_inject_raw(ch, 128);
    int16_t ddegc = 0;
    TEST_ASSERT_EQUAL_INT(WINK_ERR_OVERTEMPERATURE, dal_ntc_read_ddegc(&dev, &ddegc));

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
}

void test_ntc_clear_faults_recovery(void) {
    dal_ntc_t dev = {0};
    dal_ntc_config_t cfg = base_cfg(s_lut_10k_3950_10k);
    cfg.debounce_count = 0;
    pal_adc_channel_t ch = init_and_get_channel(&dev, &cfg);

    /* Latch an open fault. */
    pal_host_adc_inject_raw(ch, 4095);
    int16_t ddegc = 0;
    TEST_ASSERT_EQUAL_INT(WINK_ERR_HARDWARE, dal_ntc_read_ddegc(&dev, &ddegc));
    TEST_ASSERT_TRUE(dev.fault_open);

    /* A normal reading still reports the latched fault. */
    pal_host_adc_inject_raw(ch, 2048);
    TEST_ASSERT_EQUAL_INT(WINK_ERR_HARDWARE, dal_ntc_read_ddegc(&dev, &ddegc));

    /* Clearing the latch lets normal readings through. */
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_clear_faults(&dev));
    TEST_ASSERT_FALSE(dev.fault_open);
    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_read_ddegc(&dev, &ddegc));
    TEST_ASSERT_EQUAL_INT16(250, ddegc);

    TEST_ASSERT_EQUAL_INT(WINK_OK, dal_ntc_deinit(&dev));
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_ntc_init_success_and_claim);
    RUN_TEST(test_ntc_init_resource_collision);
    RUN_TEST(test_ntc_deinit_release);
    RUN_TEST(test_ntc_read_degc_b_curve_accuracy);
    RUN_TEST(test_ntc_lut_interpolation);
    RUN_TEST(test_ntc_read_ddegc_null_lut_returns_invalid_state);
    RUN_TEST(test_ntc_open_circuit_debounce);
    RUN_TEST(test_ntc_short_circuit_pull_down);
    RUN_TEST(test_ntc_differential_unsupported);
    RUN_TEST(test_ntc_overtemperature_cutoff);
    RUN_TEST(test_ntc_clear_faults_recovery);
    return UNITY_END();
}

#if defined(_MSC_VER)
#  pragma warning(pop)
#endif
