// [AUTO-GENERATED by @wink-ai/unisim-ui/generator. DO NOT EDIT MANUALLY.]
// Source: wokwi-buzzer
import type { PinsOverlayMap } from '@wink-ai/unisim-ui';

export const BUZZER_AUTOGEN_SIZE = Object.freeze({
  width: 75,
  height: 90,
});

export const BUZZER_AUTOGEN_OVERLAY: Readonly<PinsOverlayMap> = Object.freeze({
  '1': Object.freeze({
    relX: 27,
    relY: 84,
    wireNet: 'primary' as const,
    defaultConnection: null,
    required: true,
  }),
  '2': Object.freeze({
    relX: 37,
    relY: 84,
    wireNet: 'gnd' as const,
    defaultConnection: 'GND' as const,
    required: false,
  }),
});
