/* SPDX-License-Identifier: LGPL-3.0-only */
/* Harvested from esp-idf v6.1@fff9895c (Apache-2.0) — factual C-ABI only, comments stripped. See NOTICE. */
/* AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY! Manifest: 542eb37a5dc3604c Source: v6.1@fff9895c Config: esp32/v6.1 */
#ifndef WINK_H_GUARD_ESP_LOG_COLOR_H
#define WINK_H_GUARD_ESP_LOG_COLOR_H
#ifndef __WINK_HARVESTED_ESP_LOG_COLOR_H__
#define __WINK_HARVESTED_ESP_LOG_COLOR_H__
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "wink_sla.h"

#include "esp_log_config.h"
#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif
/* --- Macros (object + allowlisted function-like; first-wins + #ifndef wrapped) --- */
#ifndef ESP_LOG_SUPPORT_COLOR
#define ESP_LOG_SUPPORT_COLOR (0)
#endif
#ifndef LOG_ANSI_CLEAR_SCREEN
#define LOG_ANSI_CLEAR_SCREEN "\033[2J"
#endif
#ifndef LOG_ANSI_COLOR
#define LOG_ANSI_COLOR(TEXT_COLOR) "\033[" TEXT_COLOR "m"
#endif
#ifndef LOG_ANSI_COLOR_BACKGROUND
#define LOG_ANSI_COLOR_BACKGROUND(TEXT_COLOR, BG_COLOR) LOG_ANSI_COLOR(TEXT_COLOR ";" BG_COLOR)
#endif
#ifndef LOG_ANSI_COLOR_BG
#define LOG_ANSI_COLOR_BG(BG_COLOR) "\033[" BG_COLOR "m"
#endif
#ifndef LOG_ANSI_COLOR_BG_BLACK
#define LOG_ANSI_COLOR_BG_BLACK "40"
#endif
#ifndef LOG_ANSI_COLOR_BG_BLUE
#define LOG_ANSI_COLOR_BG_BLUE "44"
#endif
#ifndef LOG_ANSI_COLOR_BG_CYAN
#define LOG_ANSI_COLOR_BG_CYAN "46"
#endif
#ifndef LOG_ANSI_COLOR_BG_DEFAULT
#define LOG_ANSI_COLOR_BG_DEFAULT "49"
#endif
#ifndef LOG_ANSI_COLOR_BG_GREEN
#define LOG_ANSI_COLOR_BG_GREEN "42"
#endif
#ifndef LOG_ANSI_COLOR_BG_MAGENTA
#define LOG_ANSI_COLOR_BG_MAGENTA "45"
#endif
#ifndef LOG_ANSI_COLOR_BG_RED
#define LOG_ANSI_COLOR_BG_RED "41"
#endif
#ifndef LOG_ANSI_COLOR_BG_WHITE
#define LOG_ANSI_COLOR_BG_WHITE "47"
#endif
#ifndef LOG_ANSI_COLOR_BG_YELLOW
#define LOG_ANSI_COLOR_BG_YELLOW "43"
#endif
#ifndef LOG_ANSI_COLOR_BLACK
#define LOG_ANSI_COLOR_BLACK "30"
#endif
#ifndef LOG_ANSI_COLOR_BLUE
#define LOG_ANSI_COLOR_BLUE "34"
#endif
#ifndef LOG_ANSI_COLOR_BOLD
#define LOG_ANSI_COLOR_BOLD(COLOR) LOG_ANSI_COLOR(LOG_ANSI_COLOR_STYLE_BOLD ";" COLOR)
#endif
#ifndef LOG_ANSI_COLOR_BOLD_BACKGROUND
#define LOG_ANSI_COLOR_BOLD_BACKGROUND(TEXT_COLOR, BG_COLOR) LOG_ANSI_COLOR_BOLD(TEXT_COLOR ";" BG_COLOR)
#endif
#ifndef LOG_ANSI_COLOR_CYAN
#define LOG_ANSI_COLOR_CYAN "36"
#endif
#ifndef LOG_ANSI_COLOR_DEFAULT
#define LOG_ANSI_COLOR_DEFAULT "39"
#endif
#ifndef LOG_ANSI_COLOR_FORMAT
#define LOG_ANSI_COLOR_FORMAT(TEXT_STYLE, TEXT_COLOR, BG_COLOR) LOG_ANSI_COLOR(TEXT_STYLE ";" TEXT_COLOR ";" BG_COLOR)
#endif
#ifndef LOG_ANSI_COLOR_GREEN
#define LOG_ANSI_COLOR_GREEN "32"
#endif
#ifndef LOG_ANSI_COLOR_ITALIC
#define LOG_ANSI_COLOR_ITALIC(COLOR) LOG_ANSI_COLOR(LOG_ANSI_COLOR_STYLE_ITALIC ";" COLOR)
#endif
#ifndef LOG_ANSI_COLOR_ITALIC_BACKGROUND
#define LOG_ANSI_COLOR_ITALIC_BACKGROUND(TEXT_COLOR, BG_COLOR) LOG_ANSI_COLOR_ITALIC(TEXT_COLOR ";" BG_COLOR)
#endif
#ifndef LOG_ANSI_COLOR_MAGENTA
#define LOG_ANSI_COLOR_MAGENTA "35"
#endif
#ifndef LOG_ANSI_COLOR_RED
#define LOG_ANSI_COLOR_RED "31"
#endif
#ifndef LOG_ANSI_COLOR_REGULAR
#define LOG_ANSI_COLOR_REGULAR(COLOR) LOG_ANSI_COLOR(LOG_ANSI_COLOR_STYLE_RESET ";" COLOR)
#endif
#ifndef LOG_ANSI_COLOR_REGULAR_BACKGROUND
#define LOG_ANSI_COLOR_REGULAR_BACKGROUND(TEXT_COLOR, BG_COLOR) LOG_ANSI_COLOR_REGULAR(TEXT_COLOR ";" BG_COLOR)
#endif
#ifndef LOG_ANSI_COLOR_RESET
#define LOG_ANSI_COLOR_RESET "\033[" LOG_ANSI_COLOR_STYLE_RESET "m"
#endif
#ifndef LOG_ANSI_COLOR_REVERSE
#define LOG_ANSI_COLOR_REVERSE "\033[" LOG_ANSI_COLOR_STYLE_REVERSE "m"
#endif
#ifndef LOG_ANSI_COLOR_STYLE_BOLD
#define LOG_ANSI_COLOR_STYLE_BOLD "1"
#endif
#ifndef LOG_ANSI_COLOR_STYLE_ITALIC
#define LOG_ANSI_COLOR_STYLE_ITALIC "3"
#endif
#ifndef LOG_ANSI_COLOR_STYLE_RESET
#define LOG_ANSI_COLOR_STYLE_RESET "0"
#endif
#ifndef LOG_ANSI_COLOR_STYLE_REVERSE
#define LOG_ANSI_COLOR_STYLE_REVERSE "7"
#endif
#ifndef LOG_ANSI_COLOR_STYLE_UNDERLINE
#define LOG_ANSI_COLOR_STYLE_UNDERLINE "4"
#endif
#ifndef LOG_ANSI_COLOR_UNDERLINE
#define LOG_ANSI_COLOR_UNDERLINE(COLOR) LOG_ANSI_COLOR(LOG_ANSI_COLOR_STYLE_UNDERLINE ";" COLOR)
#endif
#ifndef LOG_ANSI_COLOR_UNDERLINE_BACKGROUND
#define LOG_ANSI_COLOR_UNDERLINE_BACKGROUND(TEXT_COLOR, BG_COLOR) LOG_ANSI_COLOR_UNDERLINE(TEXT_COLOR ";" BG_COLOR)
#endif
#ifndef LOG_ANSI_COLOR_WHITE
#define LOG_ANSI_COLOR_WHITE "37"
#endif
#ifndef LOG_ANSI_COLOR_YELLOW
#define LOG_ANSI_COLOR_YELLOW "33"
#endif
#ifndef LOG_ANSI_SET_CURSOR_HOME
#define LOG_ANSI_SET_CURSOR_HOME "\033[H"
#endif
#ifndef LOG_BOLD
#define LOG_BOLD(COLOR) LOG_ANSI_COLOR_BOLD(COLOR)
#endif
#ifndef LOG_COLOR
#define LOG_COLOR(COLOR) LOG_ANSI_COLOR_REGULAR(COLOR)
#endif
#ifndef LOG_COLOR_BLACK
#define LOG_COLOR_BLACK LOG_ANSI_COLOR_BLACK
#endif
#ifndef LOG_COLOR_BLUE
#define LOG_COLOR_BLUE LOG_ANSI_COLOR_BLUE
#endif
#ifndef LOG_COLOR_BROWN
#define LOG_COLOR_BROWN LOG_ANSI_COLOR_YELLOW
#endif
#ifndef LOG_COLOR_CYAN
#define LOG_COLOR_CYAN LOG_ANSI_COLOR_CYAN
#endif
#ifndef LOG_COLOR_D
#define LOG_COLOR_D ""
#endif
#ifndef LOG_COLOR_E
#define LOG_COLOR_E LOG_ANSI_COLOR_REGULAR(LOG_COLOR_RED)
#endif
#ifndef LOG_COLOR_GREEN
#define LOG_COLOR_GREEN LOG_ANSI_COLOR_GREEN
#endif
#ifndef LOG_COLOR_I
#define LOG_COLOR_I LOG_ANSI_COLOR_REGULAR(LOG_COLOR_GREEN)
#endif
#ifndef LOG_COLOR_MAGENTA
#define LOG_COLOR_MAGENTA LOG_ANSI_COLOR_MAGENTA
#endif
#ifndef LOG_COLOR_PURPLE
#define LOG_COLOR_PURPLE LOG_ANSI_COLOR_MAGENTA
#endif
#ifndef LOG_COLOR_RED
#define LOG_COLOR_RED LOG_ANSI_COLOR_RED
#endif
#ifndef LOG_COLOR_V
#define LOG_COLOR_V ""
#endif
#ifndef LOG_COLOR_W
#define LOG_COLOR_W LOG_ANSI_COLOR_REGULAR(LOG_COLOR_YELLOW)
#endif
#ifndef LOG_COLOR_WHITE
#define LOG_COLOR_WHITE LOG_ANSI_COLOR_WHITE
#endif
#ifndef LOG_COLOR_YELLOW
#define LOG_COLOR_YELLOW LOG_ANSI_COLOR_YELLOW
#endif
#ifndef LOG_ITALIC
#define LOG_ITALIC(COLOR) LOG_ANSI_COLOR_ITALIC(COLOR)
#endif
#ifndef LOG_RESET_COLOR
#define LOG_RESET_COLOR LOG_ANSI_COLOR_RESET
#endif
#ifndef LOG_UNDERLINE
#define LOG_UNDERLINE(COLOR) LOG_ANSI_COLOR_UNDERLINE(COLOR)
#endif

/* --- Enums (implicit values backfilled; ABI attrs preserved) --- */

/* --- Structs & Typedefs (merged, source order preserved for C forward refs) --- */



#ifdef __cplusplus
}
#endif
#endif /* __WINK_HARVESTED_ESP_LOG_COLOR_H__ */
#endif /* WINK_H_GUARD_ESP_LOG_COLOR_H */
