# SPDX-License-Identifier: LGPL-3.0-only
# Single source of truth for ESP-IDF simulation target selection (ADR-0085 D3 / ADR-0087).
# Input: WINK_ESP_TARGET (CMake cache, e.g. -DWINK_ESP_TARGET=esp32c3; default esp32).
# Output: WINK_ESP_TARGET_INCLUDE_DIR / WINK_IDF_TARGET_DEFINE / WINK_IDF_TARGET_STRING_DEFINE.
# Consumers: frameworks/esp_idf/esp_idf_sources.cmake, frameworks/esp_idf/CMakeLists.txt,
#            test/wasm/esp_idf_wasm_compile.cmake.

if(NOT DEFINED WINK_ESP_TARGET)
    set(WINK_ESP_TARGET "esp32")
endif()

string(TOUPPER "${WINK_ESP_TARGET}" WINK_ESP_TARGET_UPPER)

set(WINK_ESP_TARGET_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/chips/${WINK_ESP_TARGET}/include")
set(WINK_IDF_TARGET_DEFINE "CONFIG_IDF_TARGET_${WINK_ESP_TARGET_UPPER}")
set(WINK_IDF_TARGET_STRING_DEFINE "CONFIG_IDF_TARGET=\"${WINK_ESP_TARGET}\"")

if(NOT EXISTS "${WINK_ESP_TARGET_INCLUDE_DIR}/soc/soc_caps.h")
    message(FATAL_ERROR
        "WINK_ESP_TARGET='${WINK_ESP_TARGET}' has no SoC capability data at "
        "${WINK_ESP_TARGET_INCLUDE_DIR}/soc/soc_caps.h. Add chips/<soc>/include/soc/ or use a supported target "
        "(see frameworks/esp_idf/channels.json).")
endif()

# Profile selection for simulation static pool capacity (ADR-0088 / ISSUE-03)
if(NOT DEFINED WINK_ESP_SIM_PROFILE)
    set(WINK_ESP_SIM_PROFILE "LITE" CACHE STRING "ESP-IDF simulation static pool profile (LITE, STANDARD, PRO)")
endif()
string(TOUPPER "${WINK_ESP_SIM_PROFILE}" _WINK_SIM_PROFILE_UPPER)
if(NOT _WINK_SIM_PROFILE_UPPER MATCHES "^(LITE|STANDARD|PRO)$")
    message(FATAL_ERROR "Invalid WINK_ESP_SIM_PROFILE='${WINK_ESP_SIM_PROFILE}'; expected LITE, STANDARD, or PRO")
endif()

if(_WINK_SIM_PROFILE_UPPER STREQUAL "STANDARD")
    set(WINK_SIM_MAX_TASKS 16)
    set(CONFIG_FREERTOS_MAX_QUEUES 24)
    set(CONFIG_FREERTOS_QUEUE_STORAGE_SIZE 2048)
    set(CONFIG_FREERTOS_MAX_SEMAPHORES 32)
    set(CONFIG_FREERTOS_MAX_EVENT_GROUPS 16)
    set(CONFIG_FREERTOS_MAX_TIMERS 20)
    set(CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 16)
    set(CONFIG_NVS_MAX_ENTRIES 32)
    set(CONFIG_ESP_SIM_HEAP_TRACKER_MAX 128)
elseif(_WINK_SIM_PROFILE_UPPER STREQUAL "PRO")
    set(WINK_SIM_MAX_TASKS 32)
    set(CONFIG_FREERTOS_MAX_QUEUES 64)
    set(CONFIG_FREERTOS_QUEUE_STORAGE_SIZE 8192)
    set(CONFIG_FREERTOS_MAX_SEMAPHORES 64)
    set(CONFIG_FREERTOS_MAX_EVENT_GROUPS 32)
    set(CONFIG_FREERTOS_MAX_TIMERS 40)
    set(CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 32)
    set(CONFIG_NVS_MAX_ENTRIES 64)
    set(CONFIG_ESP_SIM_HEAP_TRACKER_MAX 256)
else() # LITE (Default: minimal memory footprint <8KB)
    set(WINK_SIM_MAX_TASKS 8)
    set(CONFIG_FREERTOS_MAX_QUEUES 8)
    set(CONFIG_FREERTOS_QUEUE_STORAGE_SIZE 512)
    set(CONFIG_FREERTOS_MAX_SEMAPHORES 16)
    set(CONFIG_FREERTOS_MAX_EVENT_GROUPS 8)
    set(CONFIG_FREERTOS_MAX_TIMERS 10)
    set(CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 8)
    set(CONFIG_NVS_MAX_ENTRIES 16)
    set(CONFIG_ESP_SIM_HEAP_TRACKER_MAX 64)
endif()

set(WINK_ESP_PROFILE_DEFINES
    CONFIG_FREERTOS_MAX_TASKS=${WINK_SIM_MAX_TASKS}
    CONFIG_FREERTOS_MAX_QUEUES=${CONFIG_FREERTOS_MAX_QUEUES}
    CONFIG_FREERTOS_QUEUE_STORAGE_SIZE=${CONFIG_FREERTOS_QUEUE_STORAGE_SIZE}
    CONFIG_FREERTOS_MAX_SEMAPHORES=${CONFIG_FREERTOS_MAX_SEMAPHORES}
    CONFIG_FREERTOS_MAX_EVENT_GROUPS=${CONFIG_FREERTOS_MAX_EVENT_GROUPS}
    CONFIG_FREERTOS_MAX_TIMERS=${CONFIG_FREERTOS_MAX_TIMERS}
    CONFIG_FREERTOS_TIMER_QUEUE_LENGTH=${CONFIG_FREERTOS_TIMER_QUEUE_LENGTH}
    CONFIG_NVS_MAX_ENTRIES=${CONFIG_NVS_MAX_ENTRIES}
    CONFIG_ESP_SIM_HEAP_TRACKER_MAX=${CONFIG_ESP_SIM_HEAP_TRACKER_MAX}
    WINK_SIM_MAX_TASKS=${WINK_SIM_MAX_TASKS}
    CACHE INTERNAL "ESP-IDF Simulation Profile Defines"
)
